### ISSUE TITLE
Execute socktap in Cohda SDK

### ISSUE THREAD

**Issue by KaHartmann** [riebl/vanetza#108]
Hi,

I would like to build vanetza and socktap for Cohda MK5 using the Cohda SDK.
I have followed the [instructions](http://www.vanetza.org/recipes/cohda-sdk-build/) and everything looks correct but I cannot execute neither the socktap-hello nor the socktap-cam application.

The error message is:
`/lib/ld-linux-armhf.so.3: No such file or directory`

I found `ld-linux-armhf.so.3` in `/home/duser/mk5/bsp/kernel/initrd/src/lib` and in  `/home/duser/mk5/bsp/kernel/initrd/src/lib/arm-linux-gnueabihf`.

Is the fault due to the cross compilation toolchain?

Thanks in advance.

**Comment by riebl** [comment]
If you have cross-compiled the executables then you can only run them on the target architecture. You can check with `readelf -h <path/to/executable>` for which machine type an executable has been built. I guess you are trying to run an ARM binary on a x86-64 machine, which fails naturally.

**Comment by KaHartmann** [comment]
Okay, thanks for the info. Because of the information on the Cohda website that you can use the SDK to develop, cross-compile and run programs for the cohda, i thought it should work despite different architectures. But don't ask me how :D
