### ISSUE TITLE
Proxy-fake-feed

### ISSUE THREAD

**Issue by Accelerand** [riebl/vanetza#112]
Hello,
this is not an issue but I would like to ask about. I compiled vanetza successfully, but I'm to 'stupid' to start the proxy-fake-feed tool. I initialize a UDP port and execute the following command: 

 # ./proxy_fake_feed 127.0.0.1 [2498]
Program exit because of bad lexical cast: source type value could not be interpreted as target
# ./proxy_fake_feed "127.0.0.1" [2498]
Program exit because of bad lexical cast: source type value could not be interpreted as target

What did I wrong rep. how can I start the tool?
Thanks in advance!

**Comment by riebl** [comment]
Hi @Accelerand,

the square brackets as mentioned by the usage instructions just indicate that the port number argument is optional. Launching by `./proxy_fake_feed 127.0.0.1 2498` should work then. However, I wonder for which purpose you intend to use this (deprecated) tool? I consider proxy_fake_feed as obsolete and a candidate for removal from the repository, actually.
