### ISSUE TITLE
I am getting this error after " make "

### ISSUE THREAD

**Issue by Aku1895** [riebl/vanetza#121]
cd vanetza
mkdir build && cd build
cmake ..
make
*********************************************************************************************
cmake ..

Boost 1.58 found.
-- Found Boost components:
   date_time
-- Boost 1.58 found.
-- Found Boost components:
   system;program_options
-- GeographicLib: using lookup code by Vanetza
-- Configuring done
-- Generating done
-- Build files have been written

make

[  1%] Built target common
[  2%] Built target net
[  2%] Built target access
[ 11%] Built target asn1_support
[ 47%] Built target asn1_its
[ 62%] Built target asn1_security
[ 84%] Built target asn1_pki
[ 84%] Built target asn1
[ 90%] Built target security
[ 93%] Built target dcc
[ 98%] Built target geonet
[ 99%] Built target btp
[ 99%] Built target facilities
[100%] Built target gnss
make[2]: *** No rule to make target '/usr/lib/libboost_system.so.1.75.0', needed by 'bin/proxy_fake_feed'.  Stop.
CMakeFiles/Makefile2:832: recipe for target 'tools/proxy_fake_feed/CMakeFiles/proxy_fake_feed.dir/all' failed
make[1]: *** [tools/proxy_fake_feed/CMakeFiles/proxy_fake_feed.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**********************************************************************************************************************************************

getting this error. !

**Comment by riebl** [comment]
You need to install */usr/lib/libboost_system.so.1.75.0* on your system, e.g. by installing the corresponding package offered by your Linux distribution.

**Comment by Aku1895** [comment]
1). How to invoke ctest in build directory ,is there any command ?
2). I need to install omnet++
and then artery 
am i right ??

**Comment by riebl** [comment]
1. `make test` or `ctest`
2. Yes, OMNeT++ is a prerequisite of Artery

**Comment by Aku1895** [comment]
for **make tes**t it is giving as -
make: *** No rule to make target 'test'.  Stop.

for  **ctest-**
*********************************
No test configuration file found!
*********************************
Usage

  ctest [options]

**Comment by riebl** [comment]
Vanetza's test targets are only enabled if its CMake option `BUILD_TESTS` is set to `ON`.
Sidenote: You don't need to build Vanetza on your own if you just want to build and use Artery. Artery automatically builds Vanetza.

**Comment by Aku1895** [comment]
1)Where and how to SET build_tests to on ... ? 
2)And how can I check in gtest.?

**Comment by riebl** [comment]
1. use `ccmake` or `cmake-gui` for editing CMake build variables
2. How can you check what?

**Comment by Aku1895** [comment]
i am getting like this
************************************************************************************************************
/Desktop/vanetza-master/build$ ccmake
Usage

  ccmake <path-to-source>
  ccmake <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'ccmake --help' for more information.

**Comment by Aku1895** [comment]
Do i need to install sumo after building artery ?

**Comment by riebl** [comment]
See http://artery.v2x-research.eu/install/: "Though not required for compiling Artery, you will also need to install SUMO."
