### ISSUE TITLE
Issues Compiling with Cohda SDK Release 17.1

### ISSUE THREAD

**Issue by jbeyerstedt** [riebl/vanetza#122]
I tried to use this project with V2X modems today by compiling with the `BUILD_SOCKTAP` and `SOCKTAP_WITH_COHDA_LLC` options. I'm using the Cohda SDK Release 17.1 (and have done a minor modification to the `FindCohda.cmake` file, because I'm compiling directly on the target).

The main issue I came across is, that `RxPowerA` does not exist in the `tMK2RxDescriptor` struct as it is used in [tools/cohda_proxy/proxy_handler.cpp line 86](https://github.com/riebl/vanetza/blob/master/tools/cohda_proxy/proxy_handler.cpp#L86).
Is this just a typo or a compatibility issue with older Cohda Stack versions? Because `RxPowerAnt1` and `RxPowerAnt2` do exist and when I change it to either of these, it compiles just fine.

Additionally, when running `sudo ./socktap -l cohda -i cw-llc0 -a ca`, an error message appears in the kernel messages for every CAM message:
```
LLC_MsgSend ERROR: Unknown send message type 136
```
Could you point me in the right direction, where I need to search for the reason behind this error?

Thanks

**Comment by riebl** [comment]
Yes, Cohda seems to have changed the names from `RxPowerA` to `RxPowerAnt1` etc. I think I will remove the old cohda_proxy soon, though.

I am more worried about the `LLC_MsgSend` error. Unfortunately, I had no time yet to work with the Cohda SDK Release 17.1. You should probably contact the Cohda Wireless support regarding this problem.

**Comment by jbeyerstedt** [comment]
Is the cohda_proxy actually needed for the socktap application? Because it gets compiled with the options mentioned above, but I don't see, how it might be used in my case.

Regarding the LLC error: I have access to some other applications, which used the LLC shared library instead of sending data to the cw-llc interfaces directly. The only obvious difference was, that socktap isn't configuring up the channel/ modem. But the documentation actually says something about having to set up the chconfig beforehand (and I have it configured, but mainly using default values). A more probable reason might be, that some things in the API have changed. Which version of the Cohda SDK/ LLC Remote is this based on?
Unfortunately I don't have time right now to take a deeper look at it. So I need to leave this open for the next few months. (I just had a quick look to be able to better plan the upcoming actions in our projects, but this will only get relevant later this year.)

**Comment by riebl** [comment]
No, cohda_proxy is a remnant from the early days of Vanetza when I needed a tool to integrate Cohda MK2 boxes to a network simulation. I consider this tool completely outdated nowadays.

I am sure that socktap worked with Cohda SDK 15, and also 16. I know that @glmax also uses/used Vanetza on Cohda units. Maybe he has some advice as well.
