### ISSUE TITLE
Not receiving GPS position over udp on socktap (skipping cam)

### ISSUE THREAD

**Issue by bseptember** [riebl/vanetza#123]
Hi @riebl 

I'm testing the socktap application on ubuntu 20.4.
I have an issue with the receiving the gps coordinates from my hardware which is sending over udp.

What I've tried and working:
I'm sending a NMEA string from one laptop to the ipaddress of the laptop that has the socktap app over a specific port and its working. Note, it also works when I use an application called GPSDforwarder from the google play store. https://github.com/tiagoshibata/Android-GPSd-Forwarder

Please note: I've replace the following line as workaround in gps_position_provider.cpp,
//fetched_position_fix.confidence = vanetza::PositionConfidence();
with,
fetched_position_fix.confidence.semi_minor = 1* si::meter;fetched_position_fix.confidence.semi_major = 2* si::meter;fetched_position_fix.confidence.orientation = north;
to get my CAM message printed...

![image](https://user-images.githubusercontent.com/68727050/111759366-2b757a00-88a6-11eb-851c-4dc164647339.png)

using gpsmon I see:
![image](https://user-images.githubusercontent.com/68727050/111759248-100a6f00-88a6-11eb-8dc4-437b2b172063.png)

when I stop the NMEA and rerun gpsmon:
![image](https://user-images.githubusercontent.com/68727050/111759476-4f38c000-88a6-11eb-8402-de1ea0cf659b.png)

when I stop the NMEA and rerun socktap:
![image](https://user-images.githubusercontent.com/68727050/111759610-71324280-88a6-11eb-8688-0c982e6257db.png)

The problem comes when I send the NMEA from my gps device. 
I've set it up so it can send data over udp to my laptop on the same network that the simulator was sending.

From gpsmon with my gps device connected i get:
![image](https://user-images.githubusercontent.com/68727050/111759990-e271f580-88a6-11eb-9210-7775ee7afcb4.png)

But from socktap app:
![image](https://user-images.githubusercontent.com/68727050/111760078-fa497980-88a6-11eb-8c38-61a43d0a5684.png)

I've noticed from gps device Im getting:
GPDTM **GPRMC** **GPVTG** GPGNS **GPGGA** GPGSA GPGSV GPGLL **GPGST** GPZDA GPGBS GPTHS GPVLW

And from NMEA simulator:
**GPGGA** **GPVTG** PTNL **GPGST** GPHDT **GPRMC**

I can see from nmea.cpp that only GPGGA and GPRMC is used. So I'm not sure why socktap app is skipping CAM message when using hardware but not from the NMEA simulator.

Is there a directory in the repo you can point me to or is there a simple solution here?

Thank you!
Brandon

**Comment by riebl** [comment]
The *nmea.cpp* file is not related to the GPS processing in *socktap*, which entirely relies on *gpsd*. The "Skipping CAM" message is printed if no position confidence is available, i.e. the branch with `fetched_position_fix.confidence = vanetza::PositionConfidence();` is hit in `GpsPositionProvider`. As far as I know, the [GST](https://gpsd.gitlab.io/gpsd/NMEA.html#_gst_gps_pseudorange_noise_statistics) sentence is the key so gpsd can fill its *epx* and *epy* error values.
Fields 3, 4, and 5 are empty in the GST sentence sent by your GPS device.

**Comment by bseptember** [comment]
Thanks for the quick response. 

I thought GST wouldn't matter since ive replaced:
fetched_position_fix.confidence = vanetza::PositionConfidence();
with,
fetched_position_fix.confidence.semi_minor = 1* si::meter;fetched_position_fix.confidence.semi_major = 2* si::meter;fetched_position_fix.confidence.orientation = north;

I've also tried forcing these values before the if statement in gps_position_provider: 
	gps_data.fix.epx=0;
	gps_data.fix.epy=0;
	gps_data.fix.epd=0;

What is strange is that the GST section in gpsmon via GPSDforwarder application sending NMEA via cellphone is also empty:
![image](https://user-images.githubusercontent.com/68727050/111776860-2bcc4000-88bb-11eb-9109-9828b464b720.png)
but socktap app is working.

when I remove the return
![image](https://user-images.githubusercontent.com/68727050/111776247-6da8b680-88ba-11eb-8af3-8c11f8f04f52.png)

I get the following output:
Can't determine size for unaligned PER encoding of type CAM because of HeadingValue sub-type

I will investigate further the different NMEA messages. I take it that as long as i get all fields in GST then the confidence messages will not be NULL?

**Comment by riebl** [comment]
Oops, I missed that you have replaced the empty `PositionConfidence` already in `GpsPositionProvider`. Are you sure that `fetched_position_fix` is actually getting updated, i.e. the conditions in line 117 of *gps_position_provider.cpp* are met?

**Comment by bseptember** [comment]
Hi @riebl 

Yes you were on the money!
I checked line 117. 
Added this before to see result: 
      std::cout<<"gps_data.status: "<<gps_data.status<<" gps_data.fix.mode: "<<gps_data.fix.mode<<" ";
![image](https://user-images.githubusercontent.com/68727050/111865780-afe0ff00-8971-11eb-960f-a2c365ef1ac8.png)

Then changed 117 from:
      if (gpsd_status(gps_data) == STATUS_FIX && gps_data.fix.mode >= MODE_2D) {
To:
      if (gpsd_status(gps_data) **>=** STATUS_FIX && gps_data.fix.mode >= MODE_2D) {
        //Force values
 	gps_data.fix.epx=0.01;
	gps_data.fix.epy=0.02;
	gps_data.fix.epd=0;
        //
   
Also there is a nan value for gps_data.fix.mode when there is no heading read via gpsd, but I do get heading when the GPS device is moving. So my workaround is not ideal, but I'm getting my CAM messages without any errors:

     if (!std::isnan(gps_data.fix.track)) {
            fetched_position_fix.course.assign(north + gps_data.fix.track * degree,north + gps_data.fix.epd * degree);
        }else{
        fetched_position_fix.course.assign(north,north);
        }
        
        
Thank you for your help! Much Appreciated.
Brandon
