### ISSUE TITLE
Socktap not sending over Cohda LLC with SDK ver16

### ISSUE THREAD

**Issue by AngokaVR** [riebl/vanetza#124]
I'm trying to get some experience with Vanetza on Cohda Mk5 units and I'm already experiencing some issues on just getting socktap to correctly send messages. Everything that follows has been compiled on the Cohda SDK ver16.

So far I have been unable to actually see any messages being transmitted by the application over LLC.
When running `bin/socktap -l cohda -i cw-llc0 -a ca`, I get the following error in the kernel messages for every message sent.
```
LLC_MsgSend ERROR: Unknown send message type 136
```

This seems to be linked to the FrameControl raw value set in [vanetza/access/g5_link_layer](https://github.com/riebl/vanetza/blob/master/vanetza/access/g5_link_layer.cpp). This obviously makes sense as this sets the message protocol, type and subtype.

When running `bin/socktap -l cohda -i cw-llc1 -a ca`, there are no errors in the kernel messages but nothing seems to be transmitting. The other units in my test setup do not receive any messages.

Am I missing a step to get Socktap to run correctly on Cohda LLC? Are there further configuration steps required to get Socktap to transmit over Cohda LLC interfaces, eg: set up a chconfig first?

Kind regards.

**Comment by riebl** [comment]
Hi @AngokaVR,

Yes, you need to configure the Cohda radio before starting socktap. I do not remember the exact settings I have used in the past and do not have access to an MK5 at the moment.
Unfortunately, I cannot say which message type setting LLC_MsgSend is specifically complaining about. "136" does not ring any bell. Maybe the Cohda Wireless support desk can give you a hint.

**Comment by AngokaVR** [comment]
Hi all,

I've figured out why the LLC_MsgSend ERROR occurs. 
In the commit on 20/10/2020 socktap: add LinkLayer abstraction (f397ab2) the layers that are converted to const_buffers changes. The old code goes from the Physical layer to the Application layer, in the new code it goes from Link layer to Application layer.
As a result all the physical header for the Cohda LLC library that is added in the code, does not get sent to the socket.

So when the LLC library tries to handle the date, it sees the 0x8800 from the FrameControl in the QoSHeader as the first byte.
It tries to match this in the switch case in LLC_MsgSend to determine the type of message and comes up with nothing as this value has no meaning to the physical layer.

The problem isn't entirely fixed by just including the Physical layer when sending the message, as this causes Stack Smashing which aborts the program.

I'll see if I can figure out a fix for that as well and maybe make a pull request for this.

Is there any reason in particular that the OSI layers sent have changed in that commit?

**Comment by riebl** [comment]
Thanks for identifying the reason for this bug! You can consider this misbehaviour a regression bug.
Can you please try if the following changes fix the problem?

- in the method `RawSocketLink::transmit`, change the two occurrences of `OsiLayer::Link` to `OsiLayer::Physical`
- initialise `layers_` with `num_osi_layers(vanetza::OsiLayer::Physical, vanetza::OsiLayer::Application);` in `raw_socket_link.hpp`

**Comment by AngokaVR** [comment]
I was just missing the change in the `raw_socket_link.hpp`

Tested this fix on the Cohda link-layer (works now) and checked on the ethernet link-layer as well (still works).

I've created a pull request for the fix.

Thanks for the help.

**Comment by riebl** [comment]
Great, thanks for your pull request!
