### ISSUE TITLE
Request for info on extension of Vanetza to support WAVE protocol stack

### ISSUE THREAD

**Issue by shrivyshya** [riebl/vanetza#126]
Hello Vanetza Team,

I understand that the current version of Vanetza implements the ETSI stack. Please may I know if there is a plan to extend Vanetza to support the WAVE IEEE 1609 stack (WSMP Network & Transport , LLC) and also the SAE J2735 DSRC Message sets (especially MSG_BasicSafetyMessage) ?

Is there already a conversation thread regarding the same question in the Vanetza issues list?

Thank you for your time!

Br,
Shrivyshya

**Comment by riebl** [comment]
Dear @shrivyshya,

I welcome any contribution concerning WAVE to Vanetza; however, I do not have any plans to implement these features on my own.
