### ISSUE TITLE
Implementing CPM in Facilities layer

### ISSUE THREAD

**Issue by yuasabe** [riebl/vanetza#131]
Hello Vanetza team,

Are there any current progress going on in implementing the newest draft for the Collective Perception (CP) service (ETSI TS 103 324 v0.0.22)?
I was interested in using Vanetza for supporting CPMs and integrating it with other autonomous driving stacks to enable V2X communication.

Thanks in advance!

**Comment by riebl** [comment]
Vanetza's main branch contains only published ASN.1 messages. Neither the referred draft nor its ASN.1 message definition is publicly available yet, e.g. at https://forge.etsi.org/rep/ITS/asn1.
You have probably noted that we bundle currently CPMs according to TR 103 562, though.
