### ISSUE TITLE
Decode CAM

### ISSUE THREAD

**Issue by laiketa6** [riebl/vanetza#133]
Hi,

I'm developing an V2X application using vanetza.

I have 2 development boards (APU2 by PC Engines), the first one which sends periodically CAM messages using socktap, and the second one that has to receive messages sent by the other board, also with socktap.

It's in the second one where I have the problem, I can receive a packet but I'm not able to decode it.  The received message is catch by the function _void RouterContext::indicate(CohesivePacket&& packet, const EthernetHeader& hdr)_ and then the packet is dropped. This is the log in this point:

![image](https://user-images.githubusercontent.com/87658079/126178350-e2953fb4-3b63-49e4-94f5-94494e3a2a55.png)

Could you explain me how to correctly decode this packet to get de CAM message??? How Can I pass it to the function _void CamApplication::indicate(const DataIndication& indication, UpPacketPtr packet)_ to processing it succesfully?

Thank you in advance.

**Comment by riebl** [comment]
Packets are dropped when something is odd with them security-wise and the router runs in "strict" mode. I guess some setting related to your certificates is wrong or missing, e.g. you do not set the `--certificate` and `--certificate-key` parameters.

**Comment by laiketa6** [comment]
Hello @riebl and thank you for your answer!

I'll check the settings related to the certificates. Could you explain me how to set this parameters and the values that have supposed to have?

**Comment by riebl** [comment]
`--certificate` specifies which (AT) certificate is used by the station, and `--certificate-key` pinpoints the file containing the matching private key. See also http://www.vanetza.org/tools/certify/ for some information about creating self-signed certificates and keys.

**Comment by laiketa6** [comment]
Hi @riebl,

I'm running dthe socktapp source code by visual studio in a remote machine. There is a way to config correctly this parameters by the source code.

Thank you

**Comment by riebl** [comment]
Just add the parameters to your launch configuration in Visual Studio. I discourage modifying the source code for such a runtime option.

**Comment by laiketa6** [comment]
Solved! Thanks @riebl.
