### ISSUE TITLE
This is NOT an ISSUE it's just a query regarding gps on socktap

### ISSUE THREAD

**Issue by Ak9318** [riebl/vanetza#135]
Hello sir I am trying use socktap for one my project.
I am not able to get to know..

1) Everything is compiled properly and working properly.
But by using sudo bin/socktap
It's giving as 
"exit because of positioning error : unknown error "

I am trying to use command --positioning static with lat and long.
But I AM NOT ABLE TO GET TO KNOW WHERE SHOULD I USE... And in which file i should Change..and what should I change and also getting confused. And how to change.
And also commands to execute on terminal 

Please help what should be done.

2)And I am using wireless. Not the router. Can it be worked on wireless. If not, is there anyway that can be used

**Comment by riebl** [comment]
*socktap* tries to connect to *gpsd* via the shared memory interface by default. If this interface is not provided, then this "unknown error" error message is common. You can pass the `--gpsd-host localhost` argument to *socktap* so it will try to connect to *gpsd* via the loopback device.

Sorry, I don't understand the second part of your enquiry. You can use `--positioning static` if your station is immobile or you don't have a GPS device at all. I also don't what you are referring to exactly by "wireless".

**Comment by Ak9318** [comment]
Yes sir. 
A little doubt as I am not properly exposed to ubuntu 
I know very little basic things on Ubuntu .

1) " You can pass the --gpsd-host localhost argument to socktap" 
This argument where should I just use it .
Is it on terminal.

2) " --positioning static " 
Where should I use this 
Is it on terminal .
Because if I am using it on terminal it is giving as " command not found " 

I know this is really basic sir. I am still learning.

**Comment by riebl** [comment]
Yes, you have to pass these arguments as command-line options, e.g. `./bin/socktap --gpsd-host localhost` when you are in the build directory with your terminal client.

**Comment by Ak9318** [comment]
Thank you sir, and
About 
" --positioning static "
How to use it 
Because if I am using it on terminal... 
It is showing as error

**Comment by riebl** [comment]
If the error message is `open: Operation not permitted` then this is not related to positioning but that your user is not allowed to access the network interface in raw mode. See http://www.vanetza.org/tools/socktap/ for details.

Running `./bin/socktap --positioning static --link-layer udp` works also with unprivileged accounts, which may be useful for testing and getting familiar with socktap.

**Comment by Ak9318** [comment]
Thanks sir ,
I went through accordingly. 
Now I am getting 
" Skipping cam, because no good position is available yet " 
Continuously

1)What can be done
2) how can I set a position.
3) In which file i need to put the location (latitude and longitude)

**Comment by riebl** [comment]
If you are using *gpsd*, move your GPS receiver to a location where it can acquire a position fix, i.e. has line of sight connections to some GPS satellites ideally.
Using the *static* position provider, the position is set via the `--latitude` and `--longitude` parameters. There is no configuration file involved.

**Comment by Ak9318** [comment]
Thanks sir,
But
1)How will I get to know if I am using gpsd.
2) I am using internet via hotspot
3) I have enabled the gps in my pc.
4) -- lat and --long didn't understand

**Comment by riebl** [comment]
1. *socktap* uses *gpsd* by default; if you do not tell it to use another position provider, you are using *gpsd*.
2. I don't see how your Internet connection fits into this.
3. Great. You can check with the `gpsmon` tool if you have a valid position fix and also see some additional data. This tool relies also on *gpsd*.
4. `./bin/socktap --positioning static --latitude 12 --longitude 34` tells *socktap* not to use GPS but assume a fixed position at 12° north and 34° east.

**Comment by Ak9318** [comment]
3) it is showing as this
![IMG_20210806_110921](https://user-images.githubusercontent.com/78783323/128461667-a225a57d-2b5d-43f0-a5b7-0d7ca2a0e5c6.jpg)


4). taking lot of time...
Stuck at the line
 Enable application ' ca ' ...

**Comment by riebl** [comment]
Looks to me as if *gpsd* does not recognise your GPS receiver.
*socktap* is not stuck but just operating silently. You can enable more verbose output by adding `--print-tx-cam` to the launch arguments. You will then see a summary of each generated CAM.

**Comment by Ak9318** [comment]
Okay sir,
1) Any suggestions on gpsd ? Like what can be done.
2) still a new learner to all theses steps would be helpful...
Thanks

**Comment by riebl** [comment]
Sorry, fixing *gpsd* issues is beyond my capacities.
Besides the instructions you can find at http://www.vanetza.org/tools/socktap/, you can also query `socktap --help` for a summary of available parameters.

**Comment by Ak9318** [comment]
Sir cannot I use proxy_fake_feed.
If I can use what are the command lines. 
I don't have a router(does this matter).?

**Comment by riebl** [comment]
*proxy_fake_feed* is entirely unrelated to *socktap* and I see no reason why you would want to use *proxy_fake_feed*. This tool is deprecated.

**Comment by Ak9318** [comment]
I cannot use it or can I ?
If yes please let me know it

**Comment by riebl** [comment]
This is getting annoying. Use it if you want to, look at the sources for the command line arguments. I am not willing to reply to your frequent uninformed questions. Good luck.
