### ISSUE TITLE
Denm messages

### ISSUE THREAD

**Issue by mlds30** [riebl/vanetza#137]
Hi, 
I was wondering if you have a class like "cam_application" but for sending denm messages instead or if you can give me any guidelines for creating one with vanetza.
Sorry for any trouble.

**Comment by maroueneboubakri** [comment]
@riebl a DEMN application added to socktap as done for CAM, does not receive any data indication, however, the router indicate a received packet. What could prevent routing the DEMN to the application ?

**Comment by riebl** [comment]
Most likely the receiving router is not located within the addressed destination area. The GeoNetworking layer is supposed to only pass up those messages to the application layer for which it is an intended recipient.
