### ISSUE TITLE
Cannot Send Correct DENM on Cohda

### ISSUE THREAD

**Issue by hsynydn** [riebl/vanetza#138]
Hi
I am working on socktap to be able to send a DENM. I am filling all necessary data fields but having trouble about time fields. I have filled the detectionTime as in here.

```cpp
asn_imax2INTEGER(&(denm.management.detectionTime), duration_cast<milliseconds>(now().time_since_epoch()).count()) );
```
When I analyzed denm.management.detectionTime (with gdb) after this conversion, its **buf** field contains the correct value of time. **size** field which indicates the size of **buf** shows 6. After I send this DENM on Cohda MK5 OBU _(32 bit ARM architecture)_ and then capture it via wireshark, I have witnessed that most significant 2 bytes has lost. But it works on x86_64 architecture as I expected.

Here is the code which I use to send DENM through down to layers

```cpp
void sendDenm(Denm message) {
    DownPacketPtr packet { new DownPacket() };
    packet->layer(OsiLayer::Application) = message.encode();

    DataRequest request;
    request.its_aid = aid::DEN;
    request.transport_type = geonet::TransportType::SHB;
    request.communication_profile = geonet::CommunicationProfile::ITS_G5;
    auto confirm = Application::request(request, std::move(packet));
    if (!confirm.accepted()) {
        throw std::runtime_error("application data request failed");
    }
}
```
Thanks in advance.

**Comment by hsynydn** [comment]
I am little bit sick so I couldn't work on this issue for some time. Today I have checked and see that it is working correctly. Thank you.

**Comment by riebl** [comment]
Thanks for your confirmation. I am closing this issue ticket then.
