### ISSUE TITLE
Adding new message types

### ISSUE THREAD

**Issue by buraksenkus** [riebl/vanetza#139]
Hi,

I want to be able to use new message types (e.g. SPAT, MAP). I have the ASN files of these messages but I don't know how to proceed. Should I add a new class for each field in the messages under the asn1 folder? If so should I do this manually? Can you help me with this?

Best regards,
Burak

**Comment by riebl** [comment]
Hi @buraksenkus,

You can add your ASN.1 files to the asn1 directory and include them to the CMake rules located in https://github.com/riebl/vanetza/blob/master/vanetza/asn1/CMakeLists.txt. If you have asn1c installed on your computer, a "generate_asn1c" target is enabled by Vanetza that will generate C code out of the ASN.1 files.
At the moment, I am using a slightly patched version of asn1c which you can find here: https://github.com/riebl/asn1c/tree/integer_uper
The classes in the vanetza/asn1 folder are just for convenience and not strictly required to encode or decode ASN.1 data structures.

Do you need released versions of SPAT and MAP? If yes, it would be great to add them to Vanetza's main branch.

**Comment by buraksenkus** [comment]
Hi again,

I've tried as you said but .c files are not created. Here is my steps:

1. I've installed asn1c from https://github.com/riebl/asn1c/tree/integer_uper repo.
2. I've added my ASN.1 files into asn1 folder.
![image](https://user-images.githubusercontent.com/19664856/149491521-30bd9348-0a7f-48c5-be55-a6390cf690d4.png)

2. I've included my files in `vanetza/asn1/CMakeLists.txt` and added some messages for looking whether it is worked or not.
![image](https://user-images.githubusercontent.com/19664856/149491864-6744ae5b-988e-491b-9b8e-013e1181bb33.png)

3.  I've run cmake with `-DVANETZA_ASN1_WITH_ASN1C=ON ..` flag and everything has gone correctly.
![image](https://user-images.githubusercontent.com/19664856/149492375-c1673768-b699-4fde-91a6-c579e3bd0530.png)

4. Finally, I've run `make` and `make install` but no new files are created inside `vanetza/asn1/its` folder.

I couldn't understand what I'm missing or doing wrong.

**Comment by riebl** [comment]
Invoking `make generate_asn1c` should do the trick. Since the Vanetza repository ships with pre-generated C sources of the ASN.1 stuff for convenience, the build system does not automatically regenerate those files every time. You need to trigger this step explicitly.

Otherwise, you seem to be on the right track! :-)

**Comment by buraksenkus** [comment]
Some variables in the ASN files that I added seem to conflict with variables in `ISO_TS_19091_CPM.asn` file. I'm currently trying to eliminate conflicted variables. I'll inform about the result. 

Thank you!

**Comment by buraksenkus** [comment]
I've resolved the problem and opened a pull request (#140). Thank you for the help!
