### ISSUE TITLE
Socktap with Cohda LLC API

### ISSUE THREAD

**Issue by maroueneboubakri** [riebl/vanetza#143]
Hello @riebl ,

I try to make socktap work with Cohda link.
I have 2 boards: In the first:
`./socktap --security none -l cohda -i cw-llc0 -a hello`
In the second:
`./socktap --security none -l cohda -i cw-llc0 -a benchmark`

The second board is supposed to increment the message counter ?
Also I notice that the device does not enter promiscuous mode.

When I read the documentation, cohda employs Cohda’s LLC API  I was expecting that the tool uses `/usr/lib/libLLC.so`
which was not the case (see below). It seems to be the same as ethernet except that it prepend MAC header ?
```
ldd socktap
        linux-vdso.so.1 (0x0000ffffa5a71000)
        libboost_system.so.1.71.0 => /usr/lib/libboost_system.so.1.71.0 (0x0000ffffa51ff000)
        libboost_program_options.so.1.71.0 => /usr/lib/libboost_program_options.so.1.71.0 (0x0000ffffa5169000)
        libgps.so.25 => /usr/lib/libgps.so.25 (0x0000ffffa513b000)
        libboost_date_time.so.1.71.0 => /usr/lib/libboost_date_time.so.1.71.0 (0x0000ffffa5119000)
        libGeographic.so.13 => /usr/local/lib/libGeographic.so.13 (0x0000ffffa5087000)
        libcryptopp.so.5.6 => /usr/local/lib64/libcryptopp.so.5.6 (0x0000ffffa49d7000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000ffffa47fd000)
        libm.so.6 => /lib/libm.so.6 (0x0000ffffa4754000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x0000ffffa4730000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x0000ffffa4700000)
        libc.so.6 => /lib/libc.so.6 (0x0000ffffa4598000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffa5a43000)
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x0000ffffa4534000)
        libsystemd.so.0 => /lib/libsystemd.so.0 (0x0000ffffa446c000)
        librt.so.1 => /lib/librt.so.1 (0x0000ffffa4454000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x0000ffffa441f000)
        libcap.so.2 => /lib/libcap.so.2 (0x0000ffffa4409000)
```
Could you provide a quick example which showcase how to use it, maybe I miss a detail.
Using tests from LLC app just works fine (sending/receiving).

Regards
Maro

**Comment by maroueneboubakri** [comment]
Regarding the Cohda LL API I understand that this referring to building the `Mk2Descriptor`. However, making sure that setting-up the good default configuration for both devices does not solve the issue.  Maybe should try manually adjust the `Mk2Descriptor` in `cohda.cpp`

**Comment by maroueneboubakri** [comment]
For some reason changing the default TxPower does not take effect, had to hardcode it `cohda.cpp` `phy.TxPacketData.TxPower = 60;`
Device A:
`./socktap --security none -l cohda -i cw-llc1  -a ca -p static --print-rx-cam`

Device B:
`./socktap --security none -l cohda -i cw-llc1  -a ca -p static --print-rx-cam`

```
CAM application received a packet with decodable content
Received CAM contains
...
```
I close this. Thank you :)

**Comment by CaglarDeniz** [comment]
Hello @maroueneboubakri, 
I'm actually at a really similar spot to where you once were. I'm trying to run the ca application from socktap on two different cohda units. However I'm unable to send or receive any packages. Also I'm seeing even less dynamically linked dependencies on my socktap binary, the following to be exact:
```
Dynamic section at offset 0x23dc7c contains 37 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libboost_program_options.so.1.69.0]
 0x00000001 (NEEDED)                     Shared library: [libboost_date_time.so.1.69.0]
 0x00000001 (NEEDED)                     Shared library: [libGeographic.so.19]
 0x00000001 (NEEDED)                     Shared library: [libcryptopp.so.8]
 0x00000001 (NEEDED)                     Shared library: [libstdc++.so.6]
 0x00000001 (NEEDED)                     Shared library: [libm.so.6]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux-armhf.so.3]
 0x0000001d (RUNPATH)                    Library runpath: [/home/duser/vanetza-deps/lib:]
```
I did use the BUILD_WITH_SOCKTAP and SOCKTAP_WITH_COHDA_LLC flags while building socktap so I don't really understand what the problem could be. I'm able to send and receive these messages through the ethernet link-layer so I'm confident its not related to gpsd and a lack of positioning data. Any help or pointers would be appreciated.

**Comment by maroueneboubakri** [comment]
Hi @CaglarDeniz,
Did you try to play with LLC tools to check if your boards are sending/receiving and understands if maybe Vanteza router is dropping the received packets for some reason ? also should not forget to configure the channels.
Regards
Maro

**Comment by CaglarDeniz** [comment]
Hi again @maroueneboubakri , 
Thanks for the quick reply! I have checked and verified that the boards receive and send packets when the example applications are running. I will try to see if the Vanetza router is dropping the packets by building with debugging flags, but I'm not really sure what you mean by configuring the channels. Is this something that I should be doing in socktap code, maybe in cohda.cpp or cohda_link.cpp?
Best Regards
Deniz

**Comment by maroueneboubakri** [comment]
If they are sending/receiving beacons so probably the router is dropping the packets, could be due geographic locations, are you using static GPS coords or reading them from the GNSS module or GPSD service, make sure they are closer. Try the same coords on both boards.

I mean configuring your V2X HW, do you have LLC tools ? chconfig, test-tx test-rx etc, I'm referring to chconfig to configure your radio. They are part of the Cohda SDK maybe.

Maro
