### ISSUE TITLE
IPv6 Implementations

### ISSUE THREAD

**Issue by alptekinkarabacak** [riebl/vanetza#146]
Hi,
Are you considering implement IPv6 protocol?

**Comment by riebl** [comment]
Why would I do that? I see no reason for yet another IPv6 implementation.

**Comment by alptekinkarabacak** [comment]
I am not sure but there are 2 indicate call in pass_up function(one is TransportDispatcher class function, the other one is in NetworkInterface but, the NetworkInterface function calls the TransportDispatcher' s indicate). In TransportDispatcher' s indicate function only BTP protocol pakets are processed. That' s why I asked you a question like that, If it is exist I can not find where IPv6 packets are processed.

**Comment by riebl** [comment]
Please note that `TransportDispatcher` and `NetworkInterface` belong to the Artery project, employing Vanetza as ITS-G5 stack. Anyhow, I have no plans to add any non-V2X protocols to Vanetza. IPv6 over GeoNetworking might be a candidate for inclusion. However, I am not aware of anyone pursuing this approach any longer. I assume that any practical deployment simply relies on cellular networks for IP traffic.
