### ISSUE TITLE
Can I get rtt,throughput and losepackets rate of v2v and v2i easily?

### ISSUE THREAD

**Issue by zcker** [riebl/vanetza#155]
I'm trying to simulate v2x environment to get rtt,throughput and losepackets rate ,I don't know whether I can do or not ,so I want to make a inquiry,thank you

**Comment by buraksenkus** [comment]
Hi,

Vanetza is just a protocol stack library. For example, the socktap application transmits the generated CAM packets via the given interface or listens for the packets coming into that interface. Therefore, the environment created here emulates just a standalone station (OBU/RSU).

What you are looking for is something beyond this scope. Of course, you can add measurement codes to the lower layers, but the measurement values ​​that will occur here are all about how you communicate the interfaces of these stations.

I'm not sure but if you are looking for a simulation environment [Artery](https://github.com/riebl/artery) might be more suitable for this kind of need. Communication between stations is handled by framework itself, only you need to do is to perform measurements. To realize packet loss, you might need to edit radio medium and propogation model settings in Artery scenario.

**Comment by zcker** [comment]
thank you for your answer anyway
