### ISSUE TITLE
Implementing encryption services in vanetza

### ISSUE THREAD

**Issue by Setahero** [riebl/vanetza#157]
Hello,

I have seen that vanetza is currently support signatures, but as far as i can see, there is no _real_ encryption (other then the stubs from ASN) done at the moment. Is this so far correct?

I am currently working in a project in the V2X context and me and my team are looking for these kind of security features in V2X  Open Source Projects. 

If its in your interest, we even could volunteer to enhance the feature list of vanetza so that we can have encryption. (I need to double check this with the rest of my team...)

Thank you in advance for your time and help!

**Comment by riebl** [comment]
Hi @Setahero,

You are right; encryption is not implemented. I am not aware of any use case (to be actually deployed) that requires confidentiality. Do you think that there is a use case for V2X encryption?
