### ISSUE TITLE
Sending the message to application layer from networking layer

### ISSUE THREAD

**Issue by ekamberoglu** [riebl/vanetza#159]
Hello,

I am very new at using Vanetza.

Here I had two goal to achieve:

- First one: sending an emergency brake light message from application layer and see if it arrives to transport layer. I achieved this goal (I implement vanetza::access::Interface and see that message was in request method of vanetza::access::Interface.)

- The second goal: sending the received  message in first step to back application layer from network layer (using Router::pass_up(const DataIndication& ind, UpPacketPtr packet)  method). Here, I would like to see the message received in the application layer is the same message that was first sent in the first step. Unfortunately, I could not figure out how to do this second goal. I am stuck here. Any help is really appreciated. Thanks in advance.

Cheers,
Ekrem

**Comment by riebl** [comment]
Hi @ekamberoglu,

you could use the `create_byte_view` function and compare the packets byte by byte with `std::equal` to check if they are truly identical.
See https://github.com/riebl/vanetza/blob/master/vanetza/net/packet_variant.hpp for the definition of these functions.
Please note that `Router::UpPacketPtr` is a `std::unique_ptr<PacketVariant>` (a combination of `ChunkPacket` or `CohesivePacket`) and `create_byte_view` exists for all three, `PacketVariant`, `ChunkPacket`, and `CohesivePacket`. Thus, `create_byte_view` can also be used for packets at `vanetza::access::Interface`, which employs `std::unique_ptr<ChunkPacket>`.

**Comment by ekamberoglu** [comment]
Hi Ribel,

Thank you very much for the response!

I had two issues here:
1. constructing the router correctly to make an indication call.
2. comparing packets

Actually, I did not clearly mention my first issue in my question. My fault :)

Here I am sharing my solution to constructing Router, I am not sure if this is right. Could you tell me if it is right? Also, I have not tested it. Thanks in advance.

`void NetworkInterface::indicate(UpPacketPtr packet, const vanetza::MacAddress& sender, const vanetza::MacAddress& destination) {
  createRouter();
  vanetza::btp::PortDispatcher port_dispatcher;

  runtime.now();
  DenmApplication denm_application(positioning, runtime);

  port_dispatcher.set_non_interactive_handler(ports::DENM, &denm_application);
  router->set_transport_handler(vanetza::geonet::UpperProtocol::BTP_B, &port_dispatcher);
  router->indicate(std::move(packet), sender, destination);
}

void NetworkInterface::createRouter() {
  initializeMib();
  runtime.now();
  router = new Router(runtime, mib);

  m_access_interface = new AccessInterface();
  m_fake_transmit_rate_control = new FakeTransmitRateControl(runtime);
  m_flow_control = new vanetza::dcc::FlowControl(runtime, *m_fake_transmit_rate_control, *m_access_interface);
  router->set_access_interface(m_flow_control);

  vanetza::PositionFix positionFix = getPositionFix();
  router->update_position(positionFix);
}

vanetza::PositionFix NetworkInterface::getPositionFix() const {
  vanetza::PositionFix positionFix;

  vanetza::units::GeoAngle latitude = -(6 + (22.48 / 60.0)) * vanetza::units::degree;
  vanetza::units::GeoAngle longitude = -(33 + (22.55 / 60.0)) * vanetza::units::degree;
  positionFix.latitude = latitude;
  positionFix.longitude = longitude;
  positionFix.timestamp = runtime.now();
  return positionFix;
}

void NetworkInterface::initializeMib() {
  mib.itsGnDefaultTrafficClass.tc_id(3); // send BEACONs with DP3
  mib.itsGnIsMobile = false;
  mib.itsGnSecurity = false;
  mib.vanetzaDeferInitialBeacon = true;
  mib.vanetzaDisableBeaconing = true;
}`


And DenmApplication.h:

`class DenmApplication : public Application {

public:
  DenmApplication(vanetza::PositionProvider &positioning, vanetza::Runtime &rt);
 
  PortType port() override;
  void indicate(const DataIndication &, UpPacketPtr) override;
  void set_interval(vanetza::Clock::duration);
  void print_received_message(bool flag);
  void print_generated_message(bool flag);

private:
  void schedule_timer();
  void on_timer(vanetza::Clock::time_point);
  vanetza::PositionProvider &positioning_;
  vanetza::Runtime &runtime_;
  vanetza::Clock::duration dam_interval_;
  bool print_rx_msg_ = false;
  bool print_tx_msg_ = false;
}`

**Comment by ekamberoglu** [comment]
Thank you very much Raphael.
