### ISSUE TITLE
Error inlcudes in vanetza .h files

### ISSUE THREAD

**Issue by Sanjaer** [riebl/vanetza#160]
Hi, I just installed vanetza in my VM (ubuntu 20.04).

After installing all dependencies, I run the following commands:
cd vanetza
mkdir build
cd build
cmake .. -DBUILD_SHARED_LIBS=ON
make all
sudo make install

I tried to compile a simple program, but the include paths failed due to the following:
my_app.h 
 #include <vanetza/asn1/cam.hpp> -> include error inside

cam.hpp
 #include <vanetza/asn1/its/CAM.h> -> include error inside

CAM.h
 #include "asn_application.h" -> this is the include that breaks the chain

I checked that after changing the relative path to an absolute path, it does find that header file properly:
 #include <vanetza/asn1/support/asn_application.h>
This problem is repeated in all header files with relative include paths instead of absolute. Maybe did I compile vanetza wrong?

**Comment by Irisbus** [comment]
How exactly are you building your program? I think the problem might be that you are missing `<vanetza_root>/vanetza/asn1/support` from your include directories.

**Comment by Sanjaer** [comment]
Hi, I'm using bazel. this is my command and my output

$ bazelisk build //src/APP-L:v2x-services
Starting local Bazel server and connecting to it...
INFO: Analyzed target //src/APP-L:v2x-services (38 packages loaded, 163 targets configured).
INFO: Found 1 target...
ERROR: /home/mobuser/workspace/v2x_services/src/APP-L/BUILD:15:11: Compiling src/APP-L/V2X-Services/V2XServices.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++14' -MD -MF ... (remaining 18 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from /usr/local/include/vanetza/asn1/cam.hpp:6,
                 from src/APP-L/V2X-Services/V2XServices.cpp:17:
/usr/local/include/vanetza/asn1/its/CAM.h:12:10: fatal error: asn_application.h: No such file or directory
   12 | #include "asn_application.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //src/APP-L:v2x-services failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.944s, Critical Path: 0.20s
INFO: 4 processes: 4 internal.
FAILED: Build did NOT complete successfully

I double checked and that file is in the absolute include path along with the rest of the headers
/usr/local/include/vanetza/asn1/support/asn_application.h

**Comment by Irisbus** [comment]
Unfortunately I am not familiar with bazel, but I stil *think* that your issue would fix if you had `/usr/local/include/vanetza/asn1/support` in your additional include directories (e.g.
```
 /usr/bin/gcc ... -I /usr/local/include/vanetza/asn1/support
```
on your command line). As I am not familiar with bazel, I do not know how to add it there.

**Comment by riebl** [comment]
I agree with @Irisbus that you have to add the *vanetza/asn1/support* path to your include search path. If you were using CMake, our CMake configuration would do this for you, see https://github.com/riebl/vanetza/blob/b78665fe6f48343996a50bc0010b675dab71adaa/vanetza/asn1/CMakeLists.txt#L180-L183

I cannot say how to achieve the same with bazel, though.

**Comment by Sanjaer** [comment]
I managed to build the library including support path. However, now I'm getting link errors regarding symbols of vanetza

error: undefined reference to 'asn_DEF_CAM'
...

I'm probably lacking a -l option, but I don't know how to link the whole of vanetza (eg: -lvanetza). 
I'm building a separate app that uses vanetza as a system installed library. Vanetza's .so files are in /usr/local/lib

**Comment by Sanjaer** [comment]
Hi again, I think it did work by adding those link options, it's just that bazel behaves in weird ways sometimes. I think we can close this now.

Solution:
To use vanetza in bazel, this worked for my app
```
    copts = ["-I/usr/local/include/vanetza/asn1/support/"],
    linkopts = ["-l/usr/local/lib/libvanetza_asn1_security.so", 
                "-l/usr/local/lib/libvanetza_asn1_pki.so",
                "-l/usr/local/lib/libvanetza_btp.so",
                "-l/usr/local/lib/libvanetza_facilities.so",
                "-l/usr/local/lib/libvanetza_asn1.so",
                "-l/usr/local/lib/libvanetza_asn1_its.so",
                "-l/usr/local/lib/libvanetza_asn1_support.so",
                "-l/usr/local/lib/libvanetza_geonet.so",
                "-l/usr/local/lib/libvanetza_dcc.so",
                "-l/usr/local/lib/libvanetza_access.so",
                "-l/usr/local/lib/libvanetza_gnss.so",
                "-l/usr/local/lib/libvanetza_security.so",
                "-l/usr/local/lib/libvanetza_net.so",
                "-l/usr/local/lib/libvanetza_common.so",
                ],
```
