### ISSUE TITLE
Autogenerate StationID

### ISSUE THREAD

**Issue by Sanjaer** [riebl/vanetza#165]
Is there a way to autogenerate the field StationID?
In Cohda this field is autogenerated based on the MAC of the station.

**Comment by riebl** [comment]
We currently have no specific function for this purpose, i.e. setting the `StationID` has to be handled by the software using Vanetza.
I would be happy if you provide such a function via a pull request extending Vanetza's facilities layer. This function could be used for https://github.com/riebl/vanetza/blob/b78665fe6f48343996a50bc0010b675dab71adaa/tools/socktap/cam_application.cpp#L72 then as well.

**Comment by Sanjaer** [comment]
Ok thanks! If I develop something worth it I'll surely push it
