### ISSUE TITLE
Recommended versions for ubuntu 16.04

### ISSUE THREAD

**Issue by Juanma-1** [riebl/vanetza#166]
Hello Raphael,

We start a new project in which we are going to use V2X with Vanetza.
The problem is the environment (Ubuntu 16.04) and tools (yocto Thud 2.6, kernel 4.14) that the manufacturer of the platform we are going to use forces us to use.
On the web site https://www.vanetza.org/how-to-build/#prerequisites there are mentioned the minimal versions to be used with Vanetza, and due to the old version for the environment and tools that we must use, we can not get this minimal versions without an effort to update the current ones.
Instead of doing this update, can you recommend "older" versions of prerequisites and Vanetza that can match and work with our version of environment and tools.
Note: we are going to cross-compile for kernel 4.14

Regards

**Comment by riebl** [comment]
Dear @Juanma-1,

Vanetza does not depend on a particular Linux kernel version, so I don't expect any problems with its 4.14 release. You will likely see a few compiler errors with the old GCC compiler (4.5?) originally shipped with Ubuntu 16.04. However, you also mention Yocto 2.6 which uses GCC 8.2 according to its release notes, which should be fine. AFAIK, Ubuntu also offers updated GCC packages and I expect any release from 4.9 and higher to be compatible.

**Comment by Juanma-1** [comment]
Thanks!!!!
