### ISSUE TITLE
ETSI standards implemented

### ISSUE THREAD

**Issue by msepulcre** [riebl/vanetza#171]
I was wondering which specific standards are implemented in Vanetza as part of the Transport and Geonetworking. I pressume that a subset of the [features and standards specified in Release 1](https://www.etsi.org/deliver/etsi_tr/101600_101699/101607/01.02.01_60/tr_101607v010201p.pdf) are implemented. 

As for BTP, is ETSI TS 102 636-5-1 V1.1.1 or ETSI EN 302 636-5-1 V2.2.1 implemented?

As for Geonetworking, is ETSI EN 302 636-4-1 V1.4.1 implemented (for the media independent part)? And is ETSI TS 102 636-4-2 V1.1.1 implemented for the media dependent part (ITS-G5)?

I am not asking about the standards used for building the CAM and DENM, since they are mentioned in the name of the asn1 files used in Vanetza, so I assume they are ETSI EN 302 637-2 V1.4.1 (for CAM) and ETSI EN 302 637-3 V1.3.1 (for DENM), both published in 2019 by ETSI.

This can be quite important for interoperability, and I could not find this information in the website nor in the code. Only in some comits I could find some information about the standards.

Thank you!

Miguel

**Comment by riebl** [comment]
Hi Miguel,

BTP follows EN 302 636-5-1 V2.2.1, GeoNetworking EN 302 636-4-1 V1.4.1 (generic) and TS 102 636-4-2 V1.3.1 (ITS-G5). Of course, that does not preclude any inadvertent deviations of Vanetza from the published specifications. However, I consider such deviations as bugs then.

Best regards
Raphael

**Comment by msepulcre** [comment]
Hi Raphael, 

Thanks a lot for your feedback. This information is very valuable.

Best regards,

Miguel
