### ISSUE TITLE
Removing Country Code from GeoNetworking address

### ISSUE THREAD

**Issue by Irisbus** [riebl/vanetza#174]
I am not 100% sure with this, but I think that the SCC (ITS-S Country Code) field in the GeoNetworking address changed to Reserved.
In [ETSI EN 302 636-4-1 v1.2.1](https://www.etsi.org/deliver/etsi_en/302600_302699/3026360401/01.02.01_30/en_3026360401v010201v.pdf) in sections 6.2 and 6.3 there is the SCC field: 
![image](https://user-images.githubusercontent.com/30217143/201306125-62751a2c-82c9-4545-9db0-26244604b2db.png)
but in versions [v1.3.1](https://www.etsi.org/deliver/etsi_en/302600_302699/3026360401/01.03.01_60/en_3026360401v010301p.pdf) and [1.4.1](https://www.etsi.org/deliver/etsi_en/302600_302699/3026360401/01.04.01_60/en_3026360401v010401p.pdf) there it is reserved:
![image](https://user-images.githubusercontent.com/30217143/201306279-9cdd7419-9f32-4f25-81de-69974715dc5c.png)

So should we change this field https://github.com/riebl/vanetza/blob/101364bce261834500edb98cfc59236c2b148e74/vanetza/geonet/address.hpp#L38 to reserved?

**Comment by riebl** [comment]
I am aware of this change in the specification of the GeoNetworking address. However, I have kept the (now deprecated) country code field for backward compatibility. As long as these 10 bits are not going to be used for another purpose, this does not hinder the handling of any 1.3.1/1.4.1 GN packets. I have added a deprecation notice for now.

**Comment by Irisbus** [comment]
Ok, thanks for the clarification.
