### ISSUE TITLE
Issue with Sensor Information Container 

### ISSUE THREAD

**Issue by MattiaAndreani** [riebl/vanetza#179]
Hi @riebl,
Thanks to your help I am now able to use Vanetza. 
I am trying to generate CPMs but I am experiencing a problem with the Sensor Information Container. I am trying to fill this container in the following way: 

vanetza::asn1::Cpm cpm;

for(int j=0; j<numSensors; j++) {
    auto sensor = asn1::allocate<SensorInformation_t>();
    ASN_SEQUENCE_ADD(cpm->cpm.cpmParameters.sensorInformationContainer, sensor);
    sensor->sensorID = j;
    sensor->type = 1;      
} 

where numSensors is the number of sensors to include. 
When the method cpm.size() is called, I get the following error: 

" terminate called after throwing an instance of 'std::runtime_error'
  what():  Can't determine size for unaligned PER encoding of type CPM because of SensorInformationContainer sub-type
Aborted (core dumped) "

I have checked in the asn1c_wrapper.cpp file and the problem is related to the following function:

std::size_t size_per(asn_TYPE_descriptor_t& td, const void* t)
{
    asn_enc_rval_t ec;
    ec = uper_encode(&td, nullptr, const_cast<void*>(t), write_null, nullptr);
    if (ec.encoded < 0) {
        const char* failed_type = ec.failed_type ? ec.failed_type->name : "unknown";
        const auto error_msg = boost::format(
                "Can't determine size for unaligned PER encoding of type %1% because of %2% sub-type")
                % td.name % failed_type;
        throw std::runtime_error(error_msg.str());
    }

    // Caution! ec.encoded are bits not bytes!
    return (ec.encoded + 7) / 8;
}

where ec = -1.
I am a bit confused since I have filled the Perceived Object Container in a similar way with no errors and I am experiencing this only with the Sensor Information Container. 
Any idea about what is generating the error?

Thank you in advance for your time

**Comment by Irisbus** [comment]
Hi, do you fill all the mandatory fields of all the containers with valid data? Have a look in the issue #82, I think you may have similar problem.

Furthermore, consider closing your last issue #177 if you solved your problem.

**Comment by MattiaAndreani** [comment]
@Irisbus thank you for the reply. I will try to look at the issue #82 and see if I can solve my problem. Meanwhile, I have closed the last issue

**Comment by MattiaAndreani** [comment]
@Irisbus thank you for your suggestion. Some mandatory fields were not filled with valid data and that was the problem
