### ISSUE TITLE
Socktap - How to send GPS coordinates from gps reciever?

### ISSUE THREAD

**Issue by Krupass** [riebl/vanetza#182]
Hello,
I successfully managed to send from one device to another static latitude and longitude with `sudo socktap --interface=wlp5s0 --security=none --applications=ca --positioning=static --latitude=48.131231 --longitude=11.45645464`. But when I send the command without the positioning, latitude and longitude, it still sends the "static" coordinates. When I check the position from GPS reciever with `cgps` or `gpsmon` I get the right coordinates.

I check the recieved coordinates with `sudo tshark -i wlp5s0 -V -T fields -e frame.number -e frame.time_delta -e eth.src -e eth.dst -e geonw.src_pos.long -e geonw.src_pos.lat -e frame.len`.

**Comment by kenog** [comment]
Hi,

did you set `SOCKTAP_WITH_GPSD` when compiling?

Best regards
Keno

**Comment by Krupass** [comment]
No, do I need to recompile or is there a way to do it without recompiling (I would prefer it)?

**Comment by kenog** [comment]
That's a cmake option which influences which code is compiled into vanetza. If the option is not set, the gpsd-related code is missing in Vanetza. So you have to recompile, yes.

**Comment by Krupass** [comment]
Ok, thank you. So when compiling again `SOCKTAP_WITH_GPSD` should be set to `ON`?

**Comment by kenog** [comment]
Yes, something like `cmake .. -DBUILD_SOCKTAP=ON -DSOCKTAP_WITH_GPSD=ON` should do it.

**Comment by Krupass** [comment]
Thank you very much

Have a nice day,
Krupas.
