### ISSUE TITLE
Recompiling error

### ISSUE THREAD

**Issue by Krupass** [riebl/vanetza#183]
Hello,
I tried to recompile with `sudo cmake .. -D BUILD_SOCKTAP=ON -D BUILD_CERTIFY=ON -D SOCKTAP_WITH_GPSD=ON -DCMAKE_PREFIX_PATH="some path" ` as advised in https://github.com/riebl/vanetza/issues/182. I got error `Could NOT find GPS (missing: GPS_INCLUDE_DIR GPS_LIBRARY)`.

Any idea how to fix this?

**Comment by riebl** [comment]
You need to have _gpsd_ installed on your computer when you enable the `SOCKTAP_WITH_GPSD` option. Ubuntu and Debian call the required package _libgps-dev_.

**Comment by Krupass** [comment]
I already used gpsd, but when I try to search libgps-dev with `apt list --installed | grep gpsd` i get 
`gpsd-clients/focal-updates,focal-security,now 3.20-8ubuntu0.4 amd64 [installed]`
`gpsd/focal-updates,focal-security,now 3.20-8ubuntu0.4 amd64 [installed]`. Does it mean i still need the libgps-dev?

**Comment by riebl** [comment]
Yes, you need the header files of _gpsd_ found in _libgps-dev_.

**Comment by Krupass** [comment]
ok, thanks

**Comment by lo-hei** [comment]
Sorry for asking but i get the same Error.

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find GPS (missing: GPS_INCLUDE_DIR GPS_LIBRARY)
```

gpsd and libgps-dev is installed.
```
gpsd-clients/focal-updates,focal-security,now 3.20-8ubuntu0.4 amd64 [installed]
gpsd/focal-updates,focal-security,now 3.20-8ubuntu0.4 amd64 [installed]

libgps-dev/focal-updates,focal-security,now 3.20-8ubuntu0.4 amd64 [installed]
```

What was your solution to the problem? @Krupass 
It seems Line 1&2 in `FindGPS.cmake` are not working correctly.

Thanks

**Comment by lo-hei** [comment]
Hm, sadly i could not find a solution. I am getting the Error 

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find GPS (missing: GPS_INCLUDE_DIR GPS_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGPS.cmake:23 (find_package_handle_standard_args)
  tools/socktap/CMakeLists.txt:61 (find_package)
```

Do i have to copy the package (for example the `gps.h` file) into the vanetza-folder? I tried to debug with `-DCMAKE_FIND_DEBUG_MOD=ON` but i seems like it is not correctly searching for the file because no line is indicating some searching for something with "gpsd" or "libgps-dev".

**Comment by riebl** [comment]
Does this error also occur with a fresh build directory after installing the gpsd packages as well?

**Comment by lo-hei** [comment]
Thank you very much for your answer.
Yes, unfortunately the error occurs even after multiple deletes and re-builds of the folder. Also a reinstallation of GPSD was tried.

**Comment by lo-hei** [comment]
I noticed following problem:

if i add add following text to the top of the `vanetza/CMakeLists.txt`:
```
# --- BEGIN TEST

include(CMakePrintHelpers)

find_path(
    GPS_INCLUDE_DIR 
    NAMES gps.h
    DOC "libgps include directory"
)

find_library(
    GPS_LIBRARY
    NAMES gps
    DOC "libgps library"
)

cmake_print_variables(GPS_INCLUDE_DIR)
cmake_print_variables(GPS_LIBRARY)

# --- END TEST
```

and then run 

```
cmake .. \
        -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-Autotalks-Craton.cmake \
        -DCMAKE_FIND_ROOT_PATH=$HOME/vanetza-deps \
        -DCMAKE_INSTALL_RPATH=\$ORIGIN/../lib \
        -DCMAKE_INSTALL_PREFIX=$HOME/vanetza-dist \
        -DBUILD_SOCKTAP=ON \
        -DSOCKTAP_WITH_AUTOTALKS=ON \
        -DSOCKTAP_WITH_GPSD=ON
```

it will not find the GPS package.
But if i just execute

```
cmake .. \
        -DBUILD_SOCKTAP=ON \
        -DSOCKTAP_WITH_AUTOTALKS=ON \
        -DSOCKTAP_WITH_GPSD=ON
```

Then it will not compile completely (obviously), but it will find the GPS library.
Maybe this is helpful to get to the bottom of the error. I also try to debug further.

**Comment by riebl** [comment]
Ah, you are cross-compiling! In that case, gpsd files are not looked up in your host system's directories. The `CMAKE_FIND_ROOT_PATH` variable tells CMake to look for such dependency files only in *$HOME/vanetza-deps*. Thus, *gps.h* and the libgps library need to be located there. Possibly, the Autotalks SDK already ships a pre-compiled version of libgps for their platform.

**Comment by lo-hei** [comment]
Sorry for asking,  but i am very new into it.
Sadly Autotalks does not provide any precompiled libgpsd-dev package. How can i cross-compile it for vanetza?

I tried to follow this instruction (https://gpsd.io/building.html#_cross_building) and copied everything into the `vanetza-deps` folder (cmake is finding all needed files) but it is not working (*/vanetza-deps/lib/libgps.so: file not recognized: file format not recognized*)
