### ISSUE TITLE
Can not send IVIM

### ISSUE THREAD

**Issue by Krupass** [riebl/vanetza#184]
Hello,
I installed vanetza and socktap yesterday and I could send IVI messages. Today I installed it on another system which should be same but when I try to send IVI with `sudo socktap -i wlp5s0 --security=none --applications=ivi --non-strict -p static` it throws: skip unknown application 'ivi'.

Any idea why?

**Comment by riebl** [comment]
Well, there is simply no "ivi" application in socktap. You have likely used a feature branch of a Vanetza fork on one system and the official branch on the other system.

**Comment by Krupass** [comment]
Well, on both systems I started with the same files downloaded from github and then:
`sudo cmake -D BUILD_SOCKTAP=ON -D BUILD_CERTIFY=ON -D SOCKTAP_WITH_GPSD=ON`
`sudo make`
`sudo make install`

Where could I miss something?
