### ISSUE TITLE
Adding Collective Perception Messages (CPM) of ETSI TS 103 324 v2.1.1

### ISSUE THREAD

**Issue by yuasabe** [riebl/vanetza#194]
Hello, thank you very much for the wonderful work of Vanetza.

As you may already know, the [ETSI Technical Specification for the Collective Perception Service and its respective Collective Perception Message (CPM) format](https://www.etsi.org/deliver/etsi_ts/103300_103399/103324/02.01.01_60/ts_103324v020101p.pdf) was released recently in June 2023.

I believe that the current CPM format supported in Vanetza is the [TR 103 562 v2.1.1](https://github.com/riebl/vanetza/blob/master/asn1/TR103562v211-CPM.asn) version. Therefore, I was considering adding the ASN1 files for the newly updated TS-version of CPM as released in the [ETSI Gitlab page](https://forge.etsi.org/rep/ITS/asn1/cpm_ts103324/-/tree/v2.1.1).

As a dependency, the ETSI ITS Common Data Dictionary (CDD) will also need to be updated to [ETSI TS 102 894-2 v2.1.1](https://forge.etsi.org/rep/ITS/asn1/cdd_ts102894_2). I believe that the current version included in Vanetza is for [ETSI TS 102 894-2 v1.3.1](https://github.com/riebl/vanetza/blob/master/asn1/TS102894-2v131-CDD.asn).

Please let me know if there are any works being done already to incorporate the newer CPMs, and if not, I would like to try opening a PR to add them.

As for the ASN1 compiler, I am currently planning on using https://github.com/mouse07410/asn1c

**Comment by riebl** [comment]
Hi @yuasabe,

I am not aware of anyone currently updating the CPM-related ASN.1 files in Vanetza. It would be great if you could submit such an update as a pull request. Please note that Vanetza also patches the files generated by asn1c on-the-fly. The asn1c version maintained by @mouse07410 should be fine.

**Comment by diogopjesus** [comment]
Hi @riebl and @yuasabe,
I also wanted to use the CPM format according to ETSI TS 103 324 v2.1.1.
For that, i removed the old CDD and only used the new one (version two), and replaced the CAM and DENM asn1 files with the recent drafts for version 2 CAMs/DENMs, available in the ETSI gitlab, that will be released this year. I disregarded MAPEM, RTCMEM, SPATEM, etc. for now, since I would also need to update the ISO dependent asn1 files.

I am currently working on integrating the Collective Perception Service in Artery based on the ETSI TS 103 324 v2.1.1, using this [pull request](https://github.com/riebl/artery/pull/252) as inspiration.

Is it worthy/useful to make a pull request with these contribuitions? Or do you have another idea in mind, for instance having Vanetza working simultaniously with both CDDs?
I have tried this solution. However, generating multiple fields with the same name will break code that is dependent on those fields inside both vanetza and artery.

**Comment by diogopjesus** [comment]
I have made a [pull request](https://github.com/riebl/vanetza/pull/199) with a possible solution to keep both versions of the Common Data Dictionary (CDD) and the Collective Perception Message (CPM).

**Comment by yuasabe** [comment]
Thank you, @diogopjesus for the update.
I haven't been able to make much progress with this, so it will be of great help for me too.

Have you been able to generate actual CPMs through the `socktap` application, for example?

Also, I think after a demo CPM app can be built, the CPM packets can be confirmed on Wireshark, but I was having trouble updating Wireshark so that it is compatible with this new CPM standard. Have you been able to look into analyzing the CPM packets with Wireshark?

**Comment by riebl** [comment]
Because all these ASN.1 specifications need to be aligned carefully to remain compatible with each other, I usually add only released and somewhat "approved" ASN.1 files to Vanetza's master. I know that testing any work-in-progress or lesser-known message formats becomes more tedious this way but it (hopefully) ensures compatibility with any production message type.

I will have a look at your PR @diogopjesus and will accept it if no use cases get broken for others.

**Comment by yuasabe** [comment]
@riebl Thank you for the feedback. 

Using the new CPM standard, I am working on creating a CPM application for Socktap. I usually confirm that the correct packets are generated by looking at the traffic through Wireshark and ensuring that they are being dissected properly. However, since this new CPM standard has only been released recently, Wireshark does not yet support it.

I've also been trying to update Wireshark to support this new CPM standard. Still, the packets generated in Socktap are not properly dissected, and it's difficult to tell if it's a problem with Wireshark or the CPM application in Socktap. 

If the CPMs sent on Socktap can be received by another Socktap application and can be decoded properly, there may be no need to explicitly check the packets on Wireshark, but still, it feels nice to be able to confirm the contents of the packets.

Do you usually use Wireshark to confirm the contents of ETSI packets?

**Comment by riebl** [comment]
Hi @yuasabe,

I have used Wireshark to verify some generated packets in the past, but it is not part of my usual workflow. Ideally, I have a message with known content (or vice versa, known message for given input data) and add these to the unit tests. Thus, the encoding/decoding of new message formats becomes part of the test suite run with every new commit. If these tests do not fail, then I feel even more confident than with Wireshark :-)

**Comment by machinelearningsite** [comment]
Hello, is there any update on this issue? I am currently working on a project that uses Vanetza as a dependency for V2X and would like to know if it supports ETSI TS 103 324 v2.1.1. Thank you.

**Comment by cjmodi306** [comment]
Hello, is there any update on this issue? I am currently working on a project that uses Vanetza as a dependency for V2X and would like to know if it supports ETSI TS 103 324 v2.1.1. Thank you.

**Comment by khevessy** [comment]
@cjmodi306 There is [this](https://github.com/riebl/vanetza/pull/235) pull request with working CPM that is yet to be merged to master, not sure that it is ready to release. Transmission and reception of generated CPMs was tested with other V2X devices.

**Comment by riebl** [comment]
Thanks to the PRs #209 and #235 I have been motivated to integrate ETSI ITS messages from Release 2. My approach is slightly different, though. 

The original PRs required to decide for one release or another at compile time. With my branch "asn1_release2" you can use both, release 1 and 2, concurrently. Name clashes are prevented by prefixing all the ITS Release 2 types with `Vanetza_ITS2_`.
Existing code based on Release 1 should not break at the moment. At some point, I might want to prefix these types as well.

Furthermore, I have slightly patched TS 103 324 v2.1.1 so it is compatible with CDD 2.2.1; it is a little bit tricky to get a compatible set of ASN.1 definitions for CAM, DENM and CPM. Is this a problem for you @cjmodi306?

I would love to hear the opinions of the original PR creators @diogopjesus and @khevessy before merging "asn1_release2" into "master".

**Comment by cjmodi306** [comment]
Hi @riebl , thank you for the release. No it is not a problem atm for me.

**Comment by khevessy** [comment]
@riebl I agree that your approach is better (I did not get to try your branch on our device though).

**Comment by riebl** [comment]
Thanks for your feedback! CPM 2.2.1 is now available in the master branch. Thus, I am closing this issue ticket. Thank you for your patience with me.
