### ISSUE TITLE
Create a tag on this repository

### ISSUE THREAD

**Issue by maroueneboubakri** [riebl/vanetza#196]
Hi @riebl,

I'm crafting a Yocto recipe to build Vanetza and I find it useful to tag current development. This helps establishing the dependencies and their versions as well. And write approrite documentation based on a specific release/tag/branch.

Thank you for considering this. 
Maro

**Comment by riebl** [comment]
Hi Maro, you might be right that the time has come to introduce some versioning to Vanetza. I am still unsure if I want semantic version numbers like "major.minor" or if "year.month" would be more suitable.
There has been a prior request for semantic versioning already, see #102.

I would be happy to hear more thoughts from the community on this issue :-)

**Comment by riebl** [comment]
Done with release 24.10 today

**Comment by maroueneboubakri** [comment]
@riebl, great ! thank you !
