### ISSUE TITLE
Can vanetza be used on wifi devices?

### ISSUE THREAD

**Issue by daniel0720** [riebl/vanetza#210]
Can vanetza be used on wifi devices? such as raspberry pi？

**Comment by riebl** [comment]
Yes, but please note that most WiFi chips do not support the IEEE 802.11p mode required for real ITS-G5 communication. However, you can run Vanetza's socktap with its UDP or TCP "link layer", which results in something like "ITS-G5 over IP".

**Comment by riebl** [comment]
Yes, the 802.11p mode has been implemented in the Linux driver for ath9k WiFi chips. If you have an ath9k WiFi card you put it into OCB mode (a 802.11p feature) for ad-hoc communication. Also, you will have then an ITS-G5 capable device and can run Vanetza on top of this hardware. But the WiFi chip built into Raspberry Pis is not compatible.

**Comment by valt2017** [comment]
Here is another attempt of ath9k and ath10 modifications: https://gitlab.com/hpi-potsdam/osm/g5-on-linux/11p-on-linux. It can be used with different Linux distributions on e.g. APU boards. Although in my opinion also mac80211 modifications will be necessary to achieve correct QoS in multicast mode.

**Comment by daniel0720** [comment]
@riebl Thank you. I'll take a look at the recipes.

**Comment by daniel0720** [comment]
@riebl I can’t buy OBUs from autotalks and cohda. Can I use OBUs from other companies? What do I need to do if I want to run vanetza on another company's OBU?

**Comment by riebl** [comment]
nfiniity's CUBE ships with Vanetza, so I guess it does not get easier than this when it comes to running Vanetza on an ITS-G5-compliant device. You will need to ask for a quote and check if it is in your price range, I have no pricing information. The cheapest solution is using ath9k but the setup is more challenging and requires some Linux knowledge. In past experiments, however, we had only mediocre communication ranges with ath9k-based devices compared to automotive-grade devices.

**Comment by daniel0720** [comment]
@riebl 
![image](https://github.com/riebl/vanetza/assets/12429142/f56662c9-ea78-4052-a5ca-ef79e8b5ee12)

Does vanetza support this product ?

**Comment by khevessy** [comment]
Isn't this Cohda MK5? [https://www.vanetza.org/recipes/cohda-sdk-build/](https://www.vanetza.org/recipes/cohda-sdk-build/)?
