### ISSUE TITLE
Certificate validation routines

### ISSUE THREAD

**Issue by kelunik** [riebl/vanetza#22]
Currently `NaiveCertificateManager::check_certificate()` checks the time constraints and other properties of the certificate. I think this logic should be moved into the `verify_service.cpp`. IMO the responsibility of a `CertificateManager` should be checking the trust-worthiness of the provided certificate (chain), but checking the chain for consistency can be moved outside, as it will be the same for all implementations (except if you want to completely disable verification, in which case `dummy_verification_service` can be used). I have duplicated most of the code in #20 for the `BasicCertificateManager`.

I'd probably change the signature to accept a `std::vector<Certificate>`, where a final implementation will probably just check whether the last certificate is a trusted root certificate.

Do you agree? I could provide a PR.

**Comment by riebl** [comment]
Yes, code duplication should be avoided.
I believe it is not enough just to check the root certificate in a certificate chain because one could send malicious messages with a valid root certificate but signing with unrelated "end" certificate. However, it might be feasible to cache the trust in certificates seen before. In the end, certificate managers will need to check trustworthiness of all kinds of `SignerInfo` (at least in protocol version 2) including single certificates and certificates chains.

**Comment by kelunik** [comment]
If the verify service checks the trust chain to be consistent, it should be enough if the certificate manager determines whether it knows one of those certificates as trust anchor. This will usually be a root CA I guess, but in case of cached intermediates it might also directly use the cached intermediate as trust anchor. A caching mechanism is probably necessary to check certificates sent without a chain which are not directly signed by a trusted root (which should never directly sign these certs).

Did you (or somebody else you know of) already had a look at [ETSI TS 103 096-3](http://www.etsi.org/deliver/etsi_ts/103000_103099/10309603/01.03.01_60/ts_10309603v010301p.pdf)?

**Comment by riebl** [comment]
I had no look at this conformance test specification in particular, but testing Vanetza with TTCN-3 (e.g. Eclipse TITAN) is on my long wish list ;-)
I also suppose that some form of caching is necessary when messages do not carry the full certificate but only its fingerprint (HashedId8).

**Comment by namnatulco** [comment]
What exactly do you mean by "consistency" checks? I'd expect that it basically constitutes verifying the correctness of each certificate in a certificate chain (i.e., whether they are correctly signed, still valid, etc). Caching this information is more problematic than you might first expect, especially when you have to deal with CRLs. You could let your caching expire regularly, but how would you select good values for that?

Maybe it's a good idea to separate the certificate chain correctness (i.e., is it correctly formatted, correctly signed, and is it ultimately trusted) from the certificate chain validity (i.e., are the certs still valid, non-revoked, are the algorithms used still safe). I'd suspect this allows you to achieve the desired code de-duplication without impacting security.

**Comment by kelunik** [comment]
@namnatulco With "consistency" checks I mean things like:

 - Are the associated application IDs of a certificate a strict subset of the parent certificate.
 - Is the restricted region (if any) completely contained in the one specified on the parent certificate.
 - Is the validity period entirely in the validity period of the parent certificate.

I think you can cache everything except for the revocation checks. A two phase verification mechanism therefore makes sense. Other than that, do you see any issues with caching trust?

**Comment by kelunik** [comment]
#20 already solves the issue for now, as it separates validation and certificate / key provisioning.

**Comment by namnatulco** [comment]
For those things I'd definitely say you can cache them. Maybe it's a good idea, code-structure-wise, to separate between static validation (such as the checks you mention, CA signature validity, etc) and dynamic verification (is the certificate valid in this time period, non-revoked, ..). Caching the static stuff shouldn't be an issue in that case. 
Separate from that, you'd obviously need checks that compare the message to the claims in the certificates, but if I understand the code correctly, that should happen in the `verify_service`.

**Comment by riebl** [comment]
A `CertificateValidator` interface exists by now and the `check_certificate` code has been moved for better reusability. Hence, I close this issue ticket.
Please feel free to open new tickets for still missing features.
