### ISSUE TITLE
Implement chain validation

### ISSUE THREAD

**Issue by kelunik** [riebl/vanetza#23]
This will require a set of features:

 - A `CertificateCache` that caches authorization CAs as well as authorization tickets.
 - Inspection of CAMs for messages that report unrecognized certificates.
 - Variable signer info to include the signer / signer digest / full chain for CAMs, DENMs should always use `certificate` according to TS 103 087 v1.2.1 (which I think is quite strange).

Optional features:

 - A `TrustCache` that caches trusted intermediates / authorization tickets, so they don't need a full validation of the chain.

Additionally, the entire certificate chain must be checked for consistency, such as:

 - The region restriction of a certificate is a subset of the region restriction of the parent certificate.
 - The validity period is completely within the validity period of the parent certificate.
 - The application IDs of the certificate are a subset of the application IDs specified by the parent certificate.

I plan to implement this.

**Comment by riebl** [comment]
At least some of the features mentioned as prerequisites features have been implemented already, e.g. `CertificateCache` and `TrustStore`.  `SignHeaderPolicy` deals with the "varibale signer info" aspect.
I do not understand what you mean by "Inspection of CAMs for messages that report unrecognized certificates", please give me a hint :-)

PS: I just want to track the progress and not put any pressure on you.

**Comment by kelunik** [comment]
Just the consistency checks are missing, and currently the root certificate isn't further inspected, so there are no time checks on that certificate currently.

Inspection of CAMs is non-sense, should be inspection of incoming messages and is already implemented.

https://github.com/riebl/vanetza/blob/19e8c35cc6f449ab81129d830e6e3bceafe5a98a/vanetza/security/verify_service.cpp#L70-L83

**Comment by kelunik** [comment]
This can be closed once #34 is merged.

For all remaining issues, there's a `TODO` in the code and certificates containing such restrictions are rejected.

**Comment by riebl** [comment]
Closing because #34 has been merged mostly.
