### ISSUE TITLE
Invalid Time for Path Point in Path History Copy Function

### ISSUE THREAD

**Issue by buraksenkus** [riebl/vanetza#236]
The `copy` function in `path_history.ipp` sets `pathDeltaTime` of `PathPoint`s using given path history. Based on the ASN file, the value of `PathDeltaTime` of `PathPoint`s must be in range [1-65535].

> PathDeltaTime ::= INTEGER (1..65535, ...)

But, when I use `addSample` function with boost's `universal_time` function, the `pathDeltaTime` is set as 0.

```
...
path_point.time = boost::posix_time::microsec_clock::universal_time();
path_history.addSample(path_point);
```

Is there an issue with the `copy` function or my `addSample` usage? Please check [our failed test case](https://github.com/VeNIT-Lab/vanetza/commit/89b48449fd96730606a35057199212d480a43dd4#diff-fdd0c3dfa8d0ff409801f2b96d4df0433b254349ba9197c7e7240c98ce9bdfa8R13) for a better understanding of the situation. 

> 32: [ RUN      ] CamFunctionsReferencePosition/1.copy_path_history
32: /home/bsenkus/venit/facilities/extern/vanetza/vanetza/facilities/tests/cam_functions.cpp:237: Failure
32: Value of: *current_path_point->pathDeltaTime >= 1
32:   Actual: false
32: Expected: true
32: [  FAILED  ] CamFunctionsReferencePosition/1.copy_path_history, where TypeParam = Vanetza_ITS2_ReferencePosition (0 ms)

If you confirm there is an issue with `copy` function, I will try to fix it in our branch and open a pull request.

**Comment by valt2017** [comment]
I had the same problem some time ago and I had to modify the !delta_time.is_negative() condition in while loop to make it work. Also I had to modify path_point->pathPosition.deltaLatitude and path_point->pathPosition.deltaLongitude conversions to obtain correct values in transmitted CAMs. I'm not sure if it's a bug or I use the copy function in incorrect manner.

**Comment by buraksenkus** [comment]
@valt2017 Yes, I also modified `!delta_time.is_negative()` call as `delta_time.total_milliseconds() >= 10`. It works now. Yet, I'm not sure if this breaks the integrity of path history data. Perhaps @riebl can comment on that.

**Comment by riebl** [comment]
You are absolutely right, the previous implementation potentially created path histories which violated the ASN.1 constraints.
I have taken @buraksenkus commits and added some further checks and refactoring to my "venitlab_path_history" branch. It would be nice if you could cross-check this branch before I merge it into "master", thanks!

**Comment by buraksenkus** [comment]
@riebl, thank you for reply. Even though I won't be able to run your branch anytime soon, I didn't see a problem when I looked through it. I'm looking forward to a merge :)

**Comment by valt2017** [comment]
I've tested with gpsfake only, but deltas in CAM messages seem to be OK now. Polyline of PathHistory reconstructed from deltas looks fine on the map.

**Comment by riebl** [comment]
Great, thanks for your feedback! I have merged it into master now.
