### ISSUE TITLE
byte_view_iterator - bug?

### ISSUE THREAD

**Issue by khevessy** [riebl/vanetza#240]
Hi,

I think there might be a bug in byte_view_iterator class. It is initialized in the byte_view_range constructor with begin and end iterators:
https://github.com/riebl/vanetza/blob/08ec1b7be6d55d0f154c2172c4c85d55f1cf03a5/vanetza/common/byte_view.cpp#L9-L14
which does this:
https://github.com/riebl/vanetza/blob/08ec1b7be6d55d0f154c2172c4c85d55f1cf03a5/vanetza/common/byte_view.hpp#L26

I see the problem with dereferencing the passed end iterator, because I think that normally, end iterator points past the end of the sequence and as such, dereferencing it is prohibited.

I am not sure how to solve this though, if we want to preserve the notion, that the raw pointer can be seen (since I think iterator does not have knowledge of underlying container). I thought of using the function `std::to_address()` in the constructor, but this is available from C++20 which is probably a dependency we don't want to introduce.

Maybe the raw pointer could be initialized from a separate method when it is valid:
```
/* class byte_view_iterator */
    void initRawPtr(void)
    {
        m_iteratorRaw = &*m_iterator;
    }
private:
    pointer m_iteratorRaw = nullptr;
    const ByteBuffer::const_iterator m_iterator;
/* class byte_view_iterator */
```
and
```
byte_view_range::byte_view_range(
        const ByteBuffer::const_iterator& begin,
        const ByteBuffer::const_iterator& end) :
    iterator_range(begin, end)
{
    this->begin().initRawPtr();
}
```
but I am not sure if this is the clean way to do this. If the raw pointer is not there though, I don't see the reason for this abstraction at all.

P.S. I discovered this when using Vanetza from MSVC debug build, as there is this check:
```
    _NODISCARD _CONSTEXPR20 reference operator*() const noexcept {
#if _ITERATOR_DEBUG_LEVEL != 0
        const auto _Mycont = static_cast<const _Myvec*>(this->_Getcont());
        _STL_VERIFY(_Ptr, "can't dereference value-initialized vector iterator");
        _STL_VERIFY(
            _Mycont->_Myfirst <= _Ptr && _Ptr < _Mycont->_Mylast, "can't dereference out of range vector iterator");
#endif // _ITERATOR_DEBUG_LEVEL != 0

        return *_Ptr;
    }
```
in Microsoft's `_Vector_const_iterator` class. This fails when decoding a received CAM message and also when creating the byte view of received data (if the buffer is just large enough).

Can you please help Raphael @riebl?

**Comment by riebl** [comment]
Hi @khevessy,

I agree with your analysis that dereferencing the end iterator should not happen. I have no MSVC environment available right now, but maybe changing `m_iterator(&*it)` to `m_iterator(boost::address_of(it))` avoids the problem?

Adding `#include <boost/core/pointer_traits.hpp>` would be much easier to accomplish right now than upgrading the requirement from C++11 to C++20 without prior notice.

**Comment by riebl** [comment]
Okay, too bad. I hoped for some Boost magic :-)
I have just pushed a bugfix commit to the master branch. Looking forward to your feedback if this works with MSVC!

**Comment by khevessy** [comment]
Fixed! Closing.
8c70334a41b2f0c7552bb71bd7c65b27e3317233 74d75e0c4f92e60448c08e19b76186645d88f0ae
