### ISSUE TITLE
security: enhance SSP handling

### ISSUE THREAD

**Issue by riebl** [riebl/vanetza#28]
certify's show-cert command comprises some SSP handling code which should be moved to vanetza::security.

**Comment by kelunik** [comment]
Which names should it use? Or should it even an enum for decoding? Maybe it should just be given a message (probably `vanetza::asn1::Cam`?) and a certificate and check whether it's valid? In that case certify would still need the code to show actual names.

**Comment by riebl** [comment]
The first parts (before the slash) of column "Permission Items" of Table 4 in EN 302 637-2 v1.3.2 make good unique names in my opinion (e.g. "speedLimit" -> camel case "SpeedLimit").
Following features would be nice:
- enum class for mapping the bit positions to certain meanings
- a stringify function for this enum (can be used by certify)
- a `checkServiceSpecificPermissions(const vanetza::asn1::Cam&, const ByteBuffer& ssp)` function

By passing SSP as byte buffer this function does not need to traverse the certificate (again) and no complicated return value is required to indicate "no CAM SSP found" and faults alike.

**Comment by riebl** [comment]
I have experimented a little bit with CAM SSP and came up with beb9dc6755d8de139339881799772b8c19352552 in my cam_ssp branch.
Does this meet your expectations (except for missing stringify)?

**Comment by kelunik** [comment]
LGTM!

**Comment by riebl** [comment]
Done, see 36ccdcc00bdd078a7664ccd54dd1e070574f4864
