### ISSUE TITLE
Compilation steps are incorrect

### ISSUE THREAD

**Issue by mrohith92** [riebl/vanetza#32]
I think the path to cmake command is wrong. Shouldn't it be:
cmake ../..

**Comment by riebl** [comment]
It has to be the path to Vanetza's root directory. If the build directory is a sub-directory of this root directory then "cmake .." is valid. Are you sure you followed exactly the description in the README? Of course, you can create your build directory wherever you want.

**Comment by mrohith92** [comment]
Yes. You're correct. My build directory was not a sub directory of the root directory. Sorry for the delayed response
