### ISSUE TITLE
Changes in CAM encoding

### ISSUE THREAD

**Issue by kelunik** [riebl/vanetza#36]
What exactly changed in CAM encoding comparing `master` with b0dedcb73a827b2ef3b0eb35280c7a77a05f924d? I can no longer decode CAMs with Wireshark correctly.

I already fixed the GeoNetworking version the Wireshark plugin expects, that seems to work fine, guess there have been no changes in the on-the-wire format, at least not in the packet types I used, or they're values that don't really matter for decoding.

| Old Decoded CAM | New Decoded CAM |
| ------------------------- | -------------------------- |
| ![image](https://user-images.githubusercontent.com/2743004/35725515-e77cf7ec-0801-11e8-9904-cd12a37821fd.png) | ![image](https://user-images.githubusercontent.com/2743004/35725532-f6400c6a-0801-11e8-82fa-0ff14454c5c2.png) |

**Comment by riebl** [comment]
The Common Data Dictionary (CDD) has changed regarding the encoding of Curvature. Our `master` branch now imports ASN.1 directly from an ETSI repository, currently we ship [revision 24](http://oldforge.etsi.org/websvn/dl.php?repname=ITS.ITS_ASN1&path=%2Ftrunk%2F&isdir=1&rev=24). There is also a ticket about the Curvature change: http://oldforge.etsi.org/mantis/view.php?id=7591

**Comment by kelunik** [comment]
Shouldn't we ship a version that's compatible with [TS 102 894-2 v1.2.1](http://www.etsi.org/deliver/etsi_ts/102800_102899/10289402/01.02.01_60/ts_10289402v010201p.pdf) until a new standard document is available?

**Comment by riebl** [comment]
We could revert to revision 20 of ETSI's ITS ASN.1 modules. Publication of the updated CDD standard is due to in about 4 months according to https://portal.etsi.org/webapp/workProgram/Report_Schedule.asp?WKI_ID=49410

**Comment by riebl** [comment]
@kelunik You might want to try branch asn1rev20.

**Comment by kelunik** [comment]
@riebl Works fine with that branch. :+1:

**Comment by riebl** [comment]
Branch asn1rev20 has been merged at e1e44fb. When CDD update is released by ETSI we can move on to a newer revision.

**Comment by erikbritto** [comment]
I am having the same trouble with Wireshark. 

![image](https://user-images.githubusercontent.com/6808002/83938054-e5956c80-a7d1-11ea-911d-f5a6aa971157.png)

**Comment by erikbritto** [comment]
How can I be assured that Vanetza packets are compatible with other ITS environments?

**Comment by riebl** [comment]
Possibly your version of Wireshark is still expecting the old CAM format?
My PCAP dumps produced by Vanetza setups look fine.

**Comment by erikbritto** [comment]
Thank you.

Em sáb, 6 de jun de 2020 11:44, Raphael Riebl <notifications@github.com>
escreveu:
