### ISSUE TITLE
Region restrictions

### ISSUE THREAD

**Issue by kelunik** [riebl/vanetza#37]
If I read [TS 103 097 v1.2.1](http://www.etsi.org/deliver/etsi_ts/103000_103099/103097/01.02.01_60/ts_103097v010201p.pdf) right, then CAMs will never include a `generation_location` and there's nothing in the document that specifies what should be done with regional restrictions for CAMs. The DENM and generic profiles include that field and explicitly define in the profile how regional restrictions should be handled.

I think this might be problematic. A packet can now include multiple locations which might contradict each other. There's a field for the position in the GN header, one in the security layer of GN and another one in CAMs. If a party sends a message with `generation_location` within its validity restriction but a CAM position near the receiver, such a message might be accepted even if the sending party isn't authorized to send such a CAM at its current position.

Posting to collect further thoughts on that topic and so we don't forget about checking the implementation.

**Comment by namnatulco** [comment]
Based most off what I know, and what I just re-read in the spec, I would expect that a `generation_location` with a CAM doesn't make any sense, since the generation location and the location within the CAM should be (nearly) equivalent. I **suspect** that the issue you point out (CAMs with false positions combined with DENMs with correct `generation_location`) is covered by a plausibility mechanism*. TS 103 097 doesn't specify those, though -- as far as I can tell it deals exclusively with the security headers and fields.

footnote: as far as I know, there are no standards for message plausibility, but I'll see whether I can find anything.

**Comment by kelunik** [comment]
Indeed, `generation_location` shouldn't be present in a GN packet that contains a CAM. My current implementation in #34 is based on the current location of the receiver simply, which avoids that problem mostly. We could just validate `generation_location` additionally to be within the constraints.

**Comment by namnatulco** [comment]
[TR 102 863](http://www.etsi.org/deliver/etsi_tr/102800_102899/102863/01.01.01_60/tr_102863v010101p.pdf) writes (section 6.4.2) that:
>NOTE: 
Methods to be used in plausibility checking and the means of reporting and managing suspect 
(implausible) information should be the subject of future ITS standardization

(see also chapter 8, where recommendations for future standards are given)

[TS 102 940](http://www.etsi.org/deliver/etsi_ts/102900_102999/102940/01.01.01_60/ts_102940v010101p.pdf) lists plausibility validation as a security service, but doesn't really say much other than that it's at the facilities layer (I believe PRESERVE also suggested this -- [this](https://www.preserve-project.eu/sites/preserve-project.eu/files/preserve-ws-etsi-status.pdf) slideset says it should be part of 102 94x).

[This](https://ec.europa.eu/information_society/newsroom/cf/dae/document.cfm?doc_id=1935) EU news document on harmonization says (with similar information regarding infrastructure broadcasts & infrastructure <-> vehicle communication):
> IEEE P1609.2 provides some high-level plausibility check mechanisms, but applications need to define the parameters to these mechanisms. Additional, more detailed plausibility checks may also be helpful.

There's a bunch of different surveys out there that look at such mechanisms (shameless plug: we published a pre-print of one some time ago, see [here](https://arxiv.org/abs/1610.06810), but there's a bunch of others out that that look at different things). 

the inteface between security and net/transport in [TS 102 723-8](http://www.etsi.org/deliver/etsi_ts/102700_102799/10272308/01.01.01_60/ts_10272308v010101p.pdf) (see section 5) does provide a large scope of logging variables, but not how this detection would happen. There is no referenced standard for CAM plausibility, so I suspect that's still in the works.

Finally, [TS 102 867](http://www.etsi.org/deliver/etsi_ts/102800_102899/102867/01.01.01_60/ts_102867v010101p.pdf) (Section 5.1.11) also talks about 1609.2 and says something about how this should be mapped to CAMs and DENMs (Section 6.2.2.*), specifically it contains this cryptic entry:
>Check Validity Based on Generation Location  ---  False  --- Generation location is in message and location relevance check is carried out by receiving entity 

I'm not sure what to make of this last piece of information unfortunately.

As someone writing a thesis in this area, I'd be very interested if you come across any standards in this direction :-)

**Comment by kelunik** [comment]
Yes, I think the best summary of consistency checks I know of is section 5.2.11.2 of [TS 102 723-8 v1.1.1](http://www.etsi.org/deliver/etsi_ts/102700_102799/10272308/01.01.01_60/ts_10272308v010101p.pdf).

**Comment by riebl** [comment]
@namnatulco I don't consider your remarks as spam but valuable information :-) Maybe this "survey" should even be copied to a markdown file located at the security module for future reference. I am afraid these github issues are forgotten pretty easily.

Looking at TS 102 723-8 reminds me that various security mechanisms are still missing. My main concern with ETSI ITS documents is often to distinguish really necessary features from those just specified for looking complete. @kelunik I appreciate your security contributions a lot that you have already provided!

**Comment by kelunik** [comment]
Closing, as regional checks have been implemented and CAMs don't contain a generation location field as initially assumed.
