### ISSUE TITLE
Position provider

### ISSUE THREAD

**Issue by kelunik** [riebl/vanetza#41]
Currently `DefaultCertificateValidator` and `Router` require location updates, but `SignHeaderPolicy` will need the position for the `generation_location`, too. Should we move `PositionProvider` from socktap into Vanetza? I think that's cleaner than adding `update` methods to each things that needs the location.

**Comment by riebl** [comment]
I have thought in this direction already as well. A generic `PositionProvider` should not return a `geonet::LongPositionVector`, though. It might be a good idea to adapt `Wgs84Point` from gnss instead (moving to common as `Wgs84Position`?) and removing the obsolete gnss stuff completely.

**Comment by riebl** [comment]
Actually, the missing component is the "Position Management" of Facilities' POTI. However, there is no specification available yet (EN 302 637-2 v1.3.2 refers to [i.14] TS 102 890-3 which does not exist). Beside the raw position it should provide confidence levels, heading/course and speed as well. A blueprint could be `gps_fix_t` of libgps, which contains enough information to create a `LongPositionVector` if needed.

**Comment by riebl** [comment]
https://github.com/riebl/vanetza/tree/position_provider is a preview of `PositionProvider`. However, I am not totally convinced of this approach: It looks strange to me that geonet depends on facilities...

**Comment by kelunik** [comment]
I left some comments on the commits. I wouldn't put it into the facilities layer, but rather the access layer, which matches http://www.etsi.org/deliver/etsi_en/302600_302699/302665/01.01.01_60/en_302665v010101p.pdf#page=15. `geonet` depending on the `access` layer is totally fine.

**Comment by riebl** [comment]
Thanks for pointing to EN 302 665 @kelunik! As I understand it, only a component speaking with a GPS receiver directly would be located in the `access` layer. Positioning data is required by many entities, though: GeoNet router, security, various ITS applications, LDM etc. so providing unified access to ego positions is a "cross-layer" topic in my opinion. There are only two cross-layers: Security and Management; it is definitely not a first-class citizen of Security. Time might have come to create a `management` directory.

**Comment by kelunik** [comment]
@riebl If the thing that directly communicates with the GPS receiver is in the access layer, which API would that have? Wouldn't that be the same API we have now + maybe a `onPositionUpdate` hook that other objects can attach to?

**Comment by riebl** [comment]
It gets even more interesting, see http://www.etsi.org/deliver/etsi_ts/102700_102799/10272303/01.01.01_60/ts_10272303v010101p.pdf where a "Communication Interface" (CI) owns a "KinematicVectorOut" to be read by the Management Entity. From my point of view the whole management layer acts as cross-layer configuration and environmental parameter database. It reliefs others layers from needing to know where data such as positions come from in detail.

I like the idea of a notification mechanism on position updates. A good implementation of such a mechanism could also be used for pseudonym changes and others. Do you have hands-on experience with Boost.Signals2? I am not eager to reinvent the wheel.

**Comment by riebl** [comment]
Just to keep things simple: Merged 4c49a6e.
A more sophisticated approach using notifications can be implemented later on.
