### ISSUE TITLE
can vanetza be built for android platform?

### ISSUE THREAD

**Issue by mrohith92** [riebl/vanetza#58]
I'm trying to build Vanetza for Android platform. Im using android ndk 16b and the cmake_toolchain_file provided by android ndk to build vanetza. The boost library dependency is giving me issue.
I successfully compiled cryptoPP and geographicLib using android ndk.
I compiled boost libraries for android using: https://github.com/moritz-wundke/Boost-for-Android/blob/master/build-android.sh

The command I used is follows:
`cmake -DCMAKE_TOOLCHAIN_FILE=$(NDK-PATH)/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DBOOST_INCLUDE_DIR=$(BOOST_PATH)/Boost-for-Android-master/build/out/armeabi-v7a/include/ -DBOOST_LIBRARY_DIR=$(BOOST_PATH)/Boost-for-Android-master/build/out/armeabi-v7a/lib  -DCryptoPP_INCLUDE_DIR=$(CRYPTOPP-PATH)/cryptopp-CRYPTOPP_5_6_5 -DCryptoPP_LIBRARY=$(CRYPTOPP-PATH)/cryptopp-CRYPTOPP_5_6_5/build  -DGeographicLib_INCLUDE_DIR=$(GEOGRAPHIC_LIB)/GeographicLib-1.48/include/ -DGeographicLib_LIBRARY_RELEASE=$(GEOGRAPHIC_LIB)/GeographicLib-1.48/build/src ../`

Here's output:

-- Check for working C compiler: /home/rohith/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/rohith/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/rohith/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/rohith/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:564 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:903 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:1571 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:37 (find_package)

CMake Warning at /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:564 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:903 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:1571 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:37 (find_package)

CMake Warning at /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:564 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:903 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:1571 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:37 (find_package)

CMake Error at /usr/local/share/cmake-3.11/Modules/FindBoost.cmake:1956 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:37 (find_package)

-- Found CryptoPP: /home/rohith/vanetza_for_android/Crypto++/cryptopp-CRYPTOPP_5_6_5 (found suitable version "5.6.5", minimum required is "5.6.1") 
-- Found GeographicLib: /home/rohith/vanetza_for_android/GeographicLib/GeographicLib-1.48/include (found suitable version "1.48", minimum required is "1.37") 
-- Could NOT find Cohda (missing: COHDA_MK2_ROOT) 
-- Skip build of socktap because of missing Boost::system dependency
-- Configuring incomplete, errors occurred!

PLEASE NOTE: Im using a old checkout.

**Comment by riebl** [comment]
Once upon a time I have built Vanetza for Android, however, the Android ecosystem has moved on since then considerably. Hence, I cannot give you up-to-date information about building Vanetza for Android. If I remember correctly I had to create custom Android.mk files for Boost.

**Comment by kelunik** [comment]
@riebl Just out of personal interest: Are there any devices you know of that support sending in the ITS-G5 frequency in OCB mode today?

**Comment by riebl** [comment]
@kelunik No, I don't know any ITS-G5 capable Android phones.

**Comment by kelunik** [comment]
Would be pretty cool to have a small Android app that shows nearby ITS-S on a map. :smile:

**Comment by mrohith92** [comment]
@riebl Thanks. I've been a able to build the boost libraries for android using android ndk. Using several different sources. But when I run cmake to build vanetza i get the same error message.
I wish Boost had a cmake build, like Cryptopp and GeographicLib

**Comment by riebl** [comment]
@mrohith92 I have built the required Boost components from source using CMake (see CMAKE_TOOLCHAIN_FILE for cross-compilation) and NDK toolchain. It's quite easy to create a custom CMakeLists.txt for Boost.date_time because it consists of only three source files. Please note that Boost.serialization is not used by upstream Vanetza anymore and Boost.system is an optional dependency.

**Comment by riebl** [comment]
No update on this, closing.
