### ISSUE TITLE
Document libgps-dev as dependency for socktap

### ISSUE THREAD

**Issue by kelunik** [riebl/vanetza#6]
Currently only the main dependencies are listed in the `README.md`, but `socktap` also needs `libgps-dev` for `cmake -D BUILD_SOCKTAP=ON ..` to succeed.

**Comment by riebl** [comment]
Yes, you are right. I am going to add a remark to the README. Thanks for pointing this out!

**Comment by riebl** [comment]
Information is added by d9bdf15c4b16d24d42dc1c8d1ba475f03eb476fa
