### ISSUE TITLE
Can I use your FindCryptoPP.cmake in closed source project?

### ISSUE THREAD

**Issue by mateuszzz88** [riebl/vanetza#61]
Hi
I found your project when searching for ready FindCryptoPP.cmake and decided it is better than other alternatives available on the Internet. I modified it slightly, keeping LGPL3 license: [here](https://github.com/mateuszzz88/FindCryptoPP.cmake/tree/master)

Can I distribute it under [more liberal license](https://choosealicense.com/licenses/mit/) so that anybody can use it in their closed source project without moral hangover?

 BTW: my change allows installation of CryptoPP in non-standard directory.

**Comment by riebl** [comment]
Hi @mateuszzz88,

feel free to distribute your modified FindCryptoPP.cmake under a more liberal license. I doubt that any CMake FindModule snippet reaches the threshold of originality.

BR, Raphael
