### ISSUE TITLE
change in gpsd API version 7

### ISSUE THREAD

**Issue by andyfleig** [riebl/vanetza#65]
The following [change][gpsd_git] of gpsd in API version 7 leads to the build error "too few arguments" in tools/socktap/gps_position_provider.cpp:
```
int gps_read(struct gps_data_t *)
```
has been replaced by 
```
int gps_read(struct gps_data_t *, char *message, int message_len)
```
My temporary fix at the moment is:
```
#if GPSD_API_MAJOR_VERSION >= 7
if (gps_read(&gps_data, NULL, 0) < 0) {
    throw gps_error(errno);
}
#else
if (gps_read(&gps_data,) < 0) {
    throw gps_error(errno);
}
#endif
```

Besides, the assertion in gps_position_provider.cpp has to be changed to accept API version 7.

[gpsd_git]:https://git.savannah.gnu.org/cgit/gpsd.git/commit/gps.h?id=6bba8b329fc7687b15863d30471d5af402467802

**Comment by riebl** [comment]
Very similar change is included in 848f8213b4a98a199c5d7201f0b12d8b298356e0. Thank you for reporting this issue and providing a solution proposal!
