### ISSUE TITLE
Issues with socktap in Ubuntu Bionic (18.04)

### ISSUE THREAD

**Issue by logoff** [riebl/vanetza#66]
Hello.

I've been working with `socktap` in Ubuntu Xenial (16.04) without any issue, but I have problems in Ubuntu Bionic (18.4).

When I launch the app I get this error:

```
Starting runtime at 2018-Nov-26 15:20:30.902372
Exit because of GPS error: unknown error
```
I cannot diagnose the issue, but it seems that it fails calling to function `gps_open(...)` [here](https://github.com/riebl/vanetza/blob/master/tools/socktap/gps_position_provider.cpp#L16) with error code 2, whatever it means.

I have checked and libgps versions differ in both distros:
- Xenial uses libgps22 ([package info](https://packages.ubuntu.com/xenial/libgps22))
- Bionic uses libgps23 ([package info](https://packages.ubuntu.com/bionic/libgps23))

I don't know if it is the issue. Anyone else could add more information to guess what is the problem?

Thank you.

**Comment by logoff** [comment]
I have investigated a bit more.

Launching the app using TCP `gpsd` socket instead of shared memory, the crash doesn't happen. I used this command:

```
bin/socktap-cam -i lo --gpsd-host localhost
```

Is the error related with shared memory usage of `gpsd`?

**Comment by riebl** [comment]
I have no experience with `gpsd` on Bionic so far. However, on my openSUSE Tumbleweed system there has been no problem with respect to the shared memory interface. Maybe some security feature is blocking access to the shared memory segment. Often such "incidents" are then logged by AppArmor or whatever is enforcing security policies. However, this is just a guess what might go wrong here…
