### ISSUE TITLE
Socktap receive CAM

### ISSUE THREAD

**Issue by procann** [riebl/vanetza#70]
Hello,

I tried to receive CAMs with socktap but the CamApplication::indicate() method does not get called.
Do I have to call this method somewhere manually? Sorry for this trivial question but I am unsure whether this has to be changed in vanetza or socktap or just my CAMs are not transmitted correctly.

Best regards,
procann

**Comment by riebl** [comment]
Hi @procann,

you don't have to call `CamApplication::indicate`  manually, it is invoked by the `PortDispatcher` located in socktap's `RouterContext`. Are you sure that data has been received at all? You may set a breakpoint at `RouterContext::pass_up` to verify this.

**Comment by procann** [comment]
Hi riebl,

you are correct. My interface does not show received Packets. Therefor it is not a fault in Socktap. Thanks a lot for your fast help!
