### ISSUE TITLE
facing problem during cloning

### ISSUE THREAD

**Issue by kanchannahar** [riebl/vanetza#73]
when i clone artery_master.
the folder of extern does not contain any file.
![inet](https://user-images.githubusercontent.com/49023220/55214516-3106c080-51b4-11e9-89f9-df5d88913f9e.JPG)

**Comment by riebl** [comment]
@kanchannahar Please report issues related to Artery on the [Artery GitHub page](https://github.com/riebl/artery). You manually trigger the set-up of git submodules with `git submodule update --init --recursive` in the Artery root directory.
