### ISSUE TITLE
Convert UpPacketPtr into vanetza::ans1::Cam

### ISSUE THREAD

**Issue by om3g4zell** [riebl/vanetza#75]
Hi,

I would like to know the way to extract the given packet in the indicate method for CAM application
```
void CamApplication::indicate(const DataIndication& indication, UpPacketPtr packet)
```
With artery we cast the given object into 
```
vanetza::asn1::Cam
```
Is it possible doing it in the same way ?

Thank you

**Comment by om3g4zell** [comment]
I did 
```
vanetza::CohesivePacket* p = boost::get<vanetza::CohesivePacket>(packet.get());
vanetza::asn1::Cam msg;
msg.decode(p->buffer());
```
Is it the right way ?

**Comment by riebl** [comment]
Yes, you can do it this way.
Please note that `p` might be a `nullptr` and `msg.decode` returns false if the decoding failed. I suggest to check these conditions.

**Comment by om3g4zell** [comment]
Hi, 
Thanks for your answer but i have a problem. From one side decode returns false and the other side true but it's wrong values. I think the packet contains all the informations (99 bytes) but i only want the application layer (only Cam)
In the `CamApplication::on_timer()` method
```
DownPacketPtr packer{new DownPacket()};
packet->layer(OsiLayer::Application) = std::move(message);

// Return 41
packet->size();
```
The size of the application layer is 41 bytes
![image](https://user-images.githubusercontent.com/16681470/60959707-fb23bd00-a308-11e9-84e8-86473dec3964.png)
Like you can see here
If this is the problem, i have trouble to only get a ByteBuffer of the application layer.
Best regards,

**Comment by riebl** [comment]
You need to pass the part of the packet belonging to the application layer to the ASN.1 decoder. `CohesivePacket::buffer` is the whole received packet including GN headers etc. You can get the application layer sub-range via `(*p)[OsiLayer::Application]` if `p` is a `CohesivePacket` pointer.

**Comment by om3g4zell** [comment]
Thanks for your answer !
It can seems dumb but how do you get the `ByteBuffer` associated from the `buffer_range` ?

**Comment by riebl** [comment]
You can create a new buffer from the buffer range. A more efficient approach would be to extend the `asn1c_wrapper` to accept a pair of byte buffer iterators as well, i.e. overloading its `decode` method.

**Comment by om3g4zell** [comment]
Thanks for you help but i don't know how to create a new buffer from the buffer range (I almost never used boost). I tried this but there are no iteration in the loop : 
```
 boost::iterator_range<ByteBuffer::iterator> bf = (*p)[OsiLayer::Application];
 ByteBuffer applicationBuffer;
 for(auto i : bf) {
      applicationBuffer.push_back(i);
 }

 bool result = msg.decode(applicationBuffer);
```

**Comment by riebl** [comment]
`ByteBuffer applicationBuffer(bf.begin(), bf.end());`

**Comment by riebl** [comment]
5f527c0 introduces decoding from a byte buffer range.
You can now write: `msg.decode(bf.begin(), bf.end());`

**Comment by om3g4zell** [comment]
Thanks for the commit ! it will be usefull ! 
I did `ByteBuffer applicationBuffer(bf.begin(), bf.end());` 
but he has a size of 0 maybe `(*p)[OsiLayer::Application];` doesn't return the good range ?

**Comment by riebl** [comment]
Oops, that's my fault. In socktap, `RouterContext`'s BTP port dispatcher strips the BTP header as last action before passing the packet to `CamApplication`. Consequently, all remaining bytes belong to the next upper layer `OsiLayer::Session`.
`auto bf = create_byte_view(*p, OsiLayer::Session, OsiLayer::Application)` will do the trick.

**Comment by om3g4zell** [comment]
It Works !!!
Thanks a lot for your help !
Your work is fantastic ! I used Artery for simulation and now i use Vanetza for the real implementation !
Great job 👍
