### ISSUE TITLE
Unable to generate aa.key

### ISSUE THREAD

**Issue by SrilekhaPavuluri** [riebl/vanetza#79]
I am trying to use CAM application with certificates. I can able to generate root.key, root.cert and root.pub , but it is showing an error while trying to generate aa.key . The error is " **error opening file for reading: aa.key** " . Please help me to proceed further.

**Comment by kelunik** [comment]
You need to generate it the same way as you generated the root key. Which command did you use?

**Comment by SrilekhaPavuluri** [comment]
I have given commands mentioned in " https://github.com/riebl/vanetza/tree/master/tools/certify " in the url. I tried generating aa.key using " bin/certify generate-aa --sign-key root.key --sign-cert root.cert --subject-key aa.key aa.cert " command as mentioned in the url.

**Comment by kelunik** [comment]
That command generates the authority certificate, you need to generate the key before running that command using `bin/certify generate-key aa.key`
