### ISSUE TITLE
Integration with Cohda SDK

### ISSUE THREAD

**Issue by SrilekhaPavuluri** [riebl/vanetza#80]
We have built socktap-cam with in Cohda SDK by enabling SOCKTAP_WITH_COHDA_SDK define. This define enables addtion of 16 header bytes in dcc_passthrough.cpp. Can anyone explain why these 16 bytes are being added?.
We are not able to receive the CAM messages in our application built on top of Cohda SDK hence trying to understand the significance of the 16 byte header.

**Comment by riebl** [comment]
`SOCKTAP_WITH_COHDA_SDK` adds Cohda Wireless' `tMK2TxDescriptor` header specifying the priority, radio channel, transmission power etc. for the packet to be sent. Please consult the documentation by Cohda Wireless for details.
Do not forget to configure your device properly before starting *socktap-cam* using the Cohda Wireless tools installed on MKx devices. Again, this is described in the MKx docs.
