### ISSUE TITLE
Socktap-Cam aplication timestamp, certificate chain and position confidence issue.

### ISSUE THREAD

**Issue by ShilpiPhadnis** [riebl/vanetza#81]
We are executing Socktap-cam application over cohda environment and facing some issues:
1. Invalid Timestamp: Timestamp generated by socktap-cam is invalid. Are we sending timestamp information?

Certificate chain used is inconsistent as chain of authorization tickets are required for receiving ITS 
to verify that the sender is authorised to send CAM messages.

Position confidence issue: How do we ensure that position.confidence is valid?
How do we provide longitute uncertainity and latitude uncertainity in nmea format?

Below is format of our NMEA file:
$GPGGA,104002.923,5231.127,N,01323.947,E,1,12,1.0,0.0,M,0.0,M,,*69
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,104002.923,A,5231.127,N,01323.947,E,000.0,000.0,150719,000.0,W*76
$GPGGA,104003.923,5231.127,N,01323.947,E,1,12,1.0,0.0,M,0.0,M,,*68
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,104003.923,A,5231.127,N,01323.947,E,4875.4,071.3,150719,000.0,W*48
$GPGGA,104004.923,5231.782,N,01325.894,E,1,12,1.0,0.0,M,0.0,M,,*6F
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,104004.923,A,5231.782,N,01325.894,E,1399.2,077.9,150719,000.0,W*49
$GPGGA,104005.923,5231.910,N,01326.496,E,1,12,1.0,0.0,M,0.0,M,,*66
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,104005.923,A,5231.910,N,01326.496,E,3817.3,142.4,150719,000.0,W*44
$GPGGA,104006.923,5230.951,N,01327.238,E,1,12,1.0,0.0,M,0.0,M,,*62
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,104006.923,A,5230.951,N,01327.238,E,5573.3,280.9,150719,000.0,W*49
$GPGGA,104007.923,5231.415,N,01324.812,E,1,12,1.0,0.0,M,0.0,M,,*6E
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,104007.923,A,5231.415,N,01324.812,E,000.0,000.0,150719,000.0,W*71
$GPGGA,104008.923,5231.415,N,01324.812,E,1,12,1.0,0.0,M,0.0,M,,*61
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,104008.923,A,5231.415,N,01324.812,E,2126.2,251.9,150719,000.0,W*44
$GPGGA,104009.923,5231.136,N,01323.957,E,1,12,1.0,0.0,M,0.0,M,,*63
$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30
$GPRMC,104009.923,A,5231.136,N,01323.957,E,2126.2,251.9,150719,000.0,W*46

and we are executing gpsfake application to feed information to socktap-cam but we are getting invalid position.confidence.

Kindly confirm what needs to be done for the same.

**Comment by glmax** [comment]
Could you please post the commands with which you generated the root cert, aa cert and authorization ticket and the command with which you start socktap-cam (to see if all certs are generated and supplied to socktap-cam correctly)?

Is your receiver also an instance of socktap-cam? If not, does it know the root and aa cert used by the sending socktap-cam instance?

**Comment by ShilpiPhadnis** [comment]
Issue is resolved after adding root and aa certificate in receiver application so closing this issue. Thanks
