### ISSUE TITLE
build socktap cpm application allocation problem

### ISSUE THREAD

**Issue by Shuleee** [riebl/vanetza#82]
Hello, I am try to build a cpm application through vanetza to make some small test, but I have encounter a problem of allocation. CPM have define CpmParameters like this:
```
typedef struct CpmParameters {
	CpmManagementContainer_t	 managementContainer;
	struct StationDataContainer	*stationDataContainer;	/* OPTIONAL */
	struct CpmParameters__sensorInformationContainer {
		A_SEQUENCE_OF(struct SensorInformation) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sensorInformationContainer;
	struct CpmParameters__perceivedObjectContainer {
		A_SEQUENCE_OF(struct PerceivedObject) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *perceivedObjectContainer;
	NumberOfPerceivedObjects_t	 numberOfPerceivedObjects;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CpmParameters_t;
```

Now I have a problem on how to create the sensorInformationContainer pointer as I can't directly allocate to it using `vanetza::asn1::allocate<>()`

For now I am doing as following :
```
SensorInformation_t* si1 = vanetza::asn1::allocate<SensorInformation_t>();

si1->id = 1;
si1->type = SensorType_radar;
si1->details.present = SensorDetails_PR_vehicleSensor;
VehicleSensor &vs1 = si1->details.choice.vehicleSensor;
vs1.xSensorOffset = XSensorOffset_negativeZeroPointZeroOneMeter;
vs1.ySensorOffset = YSensorOffset_zeroPointZeroOneMeter;

ASN_SEQUENCE_ADD(cpm.cpmParameters.sensorInformationContainer,si1);
```

But I find out this sensorinfomationcontainer is not added to the cpm message as I can't allocate a space for it.

I am just a beginner on this and didn't find out any other useful information online.
Hope I can get some advices.

**Comment by riebl** [comment]
Dear @Shuleee,

please note that your problem is actually related to `asn1c`. Unfortunately, its documentation is also scarce.
In your particular case, the `sensorInformationContainer` is an optional element of `cpmParameters`, i.e. you will need to allocate that field manually before adding `SensorInformation` elements to it. According to your code fragment, allocation should be possible via `vanetza::asn1::allocate<CpmParamaters__sensorInformationContainer>()`.
I guess `cpm.cpmParameters.sensorInformationContainer` is still a NULL pointer when you call `ASN_SEQUENCE_ADD` and thus nothing happens. If you check the return value of your `ASN_SEQUENCE_ADD` call, I assume its -1 (error) and `errno` equals `EINVAL`.

**Comment by Shuleee** [comment]
Dear @riebl 
Thanks for your fast reply, you are right about my `ASN_SEQUENCE_ADD` call, it is -1 because `cpm.cpmParameters.sensorInformationContainer` is NULL pointer.
I have tried what you suggestion, and I also print the address out to verify if it is well allocated,
also I print the output of ASN_SEQUENCE_ADD as following:

```
cpm.cpmParameters.sensorInformationContainer = vanetza::asn1::allocate<CpmParameters::CpmParameters__sensorInformationContainer>();
std::cout<< cpm.cpmParameters.sensorInformationContainer <<std::endl;

int flag = ASN_SEQUENCE_ADD(cpm.cpmParameters.sensorInformationContainer,si1);
std::cout<< flag <<std::endl;

```
But the output I got is like this, the first packet is the beacon and then the allocated address for the cpm.cpmParameters.sensorInformationContainer and the flag is the returned value of ASN_SEQUENCE_ADD. 
```
sent packet to ff:ff:ff:ff:ff:ff (50 bytes)
0x56147187a9b0
0
Exit: Can't determine size for unaligned PER encoding of type CPM because of sensorInformationContainer sub-type
```
Do you have some idea on how this happens. Thanks a lot

**Comment by riebl** [comment]
Is the `SensorInformation` element itself encodable? You may try this by calling `vanetza::asn1::encode(asn_DEF_SensorInformation, si1)`.

**Comment by Shuleee** [comment]
Hi @riebl 
I have to say I am not so good at asn1, 
I have tried two ways:

1. I tried to put `vanetza::asn1::encode(asn_DEF_SensorInformation, si1)` just before the ASN_SEQUENCE_ADD to test it, but I get this output error now:
`Exit: Unaligned PER encoding of type SensorInformation failed because of vehicleSensorProperties sub-type`


2. Also if I try to put this line `vanetza::asn1::encode(asn_DEF_SensorInformation,si1);` after the allocation of sensorInformation and before adding the content of it like this:

```
    SensorInformation_t* si1 = vanetza::asn1::allocate<SensorInformation_t>();
    vanetza::asn1::encode(asn_DEF_SensorInformation,si1);
    // add content in the sensorinformation 1
    si1->id = 1;
    si1->type = SensorType_radar;
    si1->details.present = SensorDetails_PR_vehicleSensor;
    VehicleSensor &vs1 = si1->details.choice.vehicleSensor;
    vs1.xSensorOffset = XSensorOffset_negativeZeroPointZeroOneMeter;
    vs1.ySensorOffset = YSensorOffset_zeroPointZeroOneMeter;

```


I got another error:` Exit: Unaligned PER encoding of type SensorInformation failed because of SensorDetails sub-type
`
From what I understood, SensorInformation is encodable itself according to :
```
/* SensorInformation */
typedef struct SensorInformation {
	Identifier_t	 id;
	SensorType_t	 type;
	BOOLEAN_t	*occupied;	/* OPTIONAL */
	SensorDetails_t	 details;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_SensorInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_SensorInformation_1[4];
```

But I think perhaps for sensorInformationContainer itself is not encodable, but I can find its asn_TYPE_descriptor_s.
So I am thinking should I find a way to encode the sensorInformationContainer or do you have some other ideas?
Thanks for your help!

**Comment by riebl** [comment]
@Shuleee Since already the encoding of `SensorInformation` fails (see its vehicleSensorProperties) you need to set all sub-fields correctly so all ASN.1 constraints of them are fulfilled. Then, you will be able to add this element and encoding of the container will succeed.
Please refer to the ASN.1 file for CPM to see each field's constraint.

**Comment by Shuleee** [comment]
Thanks a lot, @riebl you are totally right! I miss a mandatory part and I didn't pay attention to it before! THANKS A LOT!
