### ISSUE TITLE
Inconsistent chain issue using socktap-cam

### ISSUE THREAD

**Issue by SrilekhaPavuluri** [riebl/vanetza#83]
We are facing inconsitent chain issue while executing socktap-cam in cohda SDK environment.
Authorization ticktets are required for receiving ITS to verify that the sender is authorised to send CAM messages.
Below are the steps that we executed:
1. Execute fakegps and cgps.
2. Execute socktap-cam with authorization ticket. We are receiving gps longitude and latitude in socktap-cam application.
3. We are facing inconsistent chain issue in receiver application.

Steps to generate authorization ticket is :
1. ./bin/certify generate-key root.key
2. ./bin/certify generate-root --subject-key root.key root.cert
3. ./bin/certify generate-key aa.key
4. ./bin/certify generate-key ticket.key
5. ./bin/certify generate-aa --sign-key root.key --sign-cert root.cert --subject-key aa.key aa.cert
6. ./bin/certify generate-ticket --sign-key aa.key --sign-cert aa.cert --subject-key ticket.key ticket.cert

Kindly confirm how to solve this issue. Is process to generate certificate is not correct?

**Comment by kelunik** [comment]
Looks fine to me. What are the inconsistency issues you're seeing?

**Comment by SrilekhaPavuluri** [comment]
We are using the generated authorization ticket to sign the CAM messages but since as TS 103 097 1.2.1, the certificate is valid for few mins and needs another authorization ticket to send the next CAM message after the validity of the previous ticket expires. How is this supported by certify tool.
Is there a way to generate and specify chain of authorization tickets to socktap-cam ?.

**Comment by kelunik** [comment]
The default validity period in certify are 7 days, you can increase it using the --days command line switch. There's no need to switch the ticket every few minutes.

What's the receiver application?

**Comment by dsvenkyTCS** [comment]
How do i provide option to generate certificate with compressed EccPoint rather than uncompressed?.

**Comment by kelunik** [comment]
You need to implement that yourself.

**Comment by riebl** [comment]
@dsvenkyTCS Please do not hijack issue tickets but open a new one with an expressive title for your specific problem. Feel free to submit a pull request if you have decided to implement a new feature :-)
