### ISSUE TITLE
"Certificate is unknown issue"

### ISSUE THREAD

**Issue by ShilpiPhadnis** [riebl/vanetza#85]
We have generated root certificate, authorization authority and authorization ticket certificate using Certify tool application but cohda stack is not able to parse data.
We provided binary hex value of root certificate to https://werkzeug.dcaiti.tu-berlin.de/etsi/ts103097/ and it is showing error "Certificate is unknown".
We believe that generated certificate is compliant with TS 103097 1.2.1 standard then why we are facing this issue.

Root certificate hex value that we had generated using socktap-cam certify tool is : 
0200040c547275737465645f526f6f74808d000004c68bc7cf4254d7621514ff5be30293777dba34d5dcbd7cf6dcfd25e15593aac0246bc7b1292e200e19e0041cdcc9736a8875c84aec069834fbd6198aa38d597001010004c68bc7cf4254d7621514ff5be30293777dba34d5dcbd7cf6dcfd25e15593aac0246bc7b1292e200e19e0041cdcc9736a8875c84aec069834fbd6198aa38d597002e02002242515011d588c3c1df6ce4c03011d36ee3605026aac01900000ffa68815dc42c001d6bfd896c39252b1e2cf90be49e1d639ed47805736ce10c9b19b4424e5f17ed44da0b8a646870bc49fece65752bf98b8f5927b01d7cc6b5454

**Comment by kelunik** [comment]
Unknown here probably just means that the validator doesn't know about the certificate, so it's not a well-known certificate. This is expected, as it's a certificate with a random key generated by you.

**Output**
```
[OK] successfully parsed hex-string: 248 bytes
[OK] successfully decoded : Certificate
[FAIL] certificate is: UNKNOWN
```

**Comment by ShilpiPhadnis** [comment]
Ok. We can close this issue.
