### ISSUE TITLE
Issue in running highway.police sample application

### ISSUE THREAD

**Issue by shalinits** [riebl/vanetza#86]
While running highway.police sample application, I had made changes related to the depart parameter as shown below in highway.rou.xml 

 It is showing as tcpip::SocketException: tcpip::Socket::recvAndCheck @ recv: peer shutdown -- in module (traci::Core) World.traci.core (id=4), at t=1.1s, event #1213

If we give departLane as 3 in either of the three vehicle ids it is crashing.The simulation ends at t=2.1s.

[highway.rou.xml.zip](https://github.com/riebl/vanetza/files/3508252/highway.rou.xml.zip)

**Comment by riebl** [comment]
This is entirely unrelated to Vanetza. Issue ticket closed.
