### ISSUE TITLE
Can vanetza be built for OpenWRT/LEDE platform?

### ISSUE THREAD

**Issue by nelsoncardona** [riebl/vanetza#87]
This is not an issue but I would like to ask about.
 
I want to build vanetza for OpenWRT/LEDE platform. Those are linux based platforms so I guess it's feasible.

Do you think is possible? Could you give some insights about the changes I need to implement?

Thanks in advance.

**Comment by riebl** [comment]
Dear @nelsoncardona,

I see no problem in building Vanetza for OpenWRT in general. However, Vanetza is mainly a C++ library plus some demo applications (e.g. socktap). Thus, you will need to create some kind of additional application to make full use of Vanetza.
Depending on the employed networking hardware and its drivers you may further need to implement your own `vanetza::access::Interface` to transmit packets with correct MAC addresses, access category/user priority, and EtherType.

Last but not least, I am happy to integrate your pull requests improving Vanetza's compatibility with the OpenWRT platform.

Best regards,
Raphael

**Comment by valt2017** [comment]
Hi, I was able to compile and run socktap demo on LEDE 17.01.6. I don't remember which versions of required libraries (crypto++, geographiclib, Boost) were directly available in OpenWrt repositories. If you compile OpenWRT, you have SDK directly available so it should not be a problem to compile them and Vanetza on your own.
