### ISSUE TITLE
Unable to decode certificates generated with certify tool

### ISSUE THREAD

**Issue by praneethshub** [riebl/vanetza#88]
I am unable to decode certificates( Eg: root, aa) generated with Certify tool. I am using online tool https://asn1.io/asn1playground/Default.aspx

I am giving ASN.1 code of Std IEEE 1609.2-2016 as input

`OSS ASN-1Step Version 9.0.1
Copyright (C) 2019 OSS Nokalva, Inc.  All rights reserved.
This product is licensed for use by "OSS Nokalva, Inc."
C0043I: 0 error messages, 0 warning messages and 0 informatory messages issued.
ASN1STEP: Decoding PDU #22 
CertificateBase SEQUENCE
  version INTEGER [length = 1]
    32
  type CertificateType ENUMERATED [length = 1]
    4
  issuer IssuerIdentifier CHOICE [length = 72]
    0x656c6c6f20576f726c6420526f6f742d43 ...
  toBeSigned ToBeSignedCertificate SEQUENCE
D0037E: Value misencoded or length wrong for value; check field 'id' (type: CertificateId) of field 'toBeSigned' (type: ToBeSignedCertificate) of PDU #22 'CertificateBase'.
S0012E: Decoding of PDU #22 failed with the return code '5'.`

Kindly suggest appropriate to ASN.1 specification to decode certificates generated using Certify tool.

**Comment by glmax** [comment]
Currently, Vanetza only supports the "old" certificate format specified in [ETSI TS 103 097 v1.2.1](https://www.etsi.org/deliver/etsi_ts/103000_103099/103097/01.02.01_60/ts_103097v010201p.pdf), see section 6 specifically for the certificate format itself. Unfortunately, this v1.2.1 does not supply a ASN1 module.

There is already an issue to remind upgrading to v1.3.1 which uses the IEEE 1609.2 format (#18).

**Comment by riebl** [comment]
Closing this issue ticket because #18 is already a related "reminder ticket".
