### ISSUE TITLE
Compile vanetza for OSX - netpacket/packet.h error

### ISSUE THREAD

**Issue by cdce8p** [riebl/vanetza#89]
I'm currently trying to compile vanetza for OSX. `CMake` works, however `make` doesn't.
```
$ make
[  0%] Built target access
[ 63%] Built target asn1
[ 65%] Built target common
Scanning dependencies of target net
[ 66%] Building CXX object vanetza/net/CMakeFiles/net.dir/sockaddr.cpp.o
/xxx/xxxx/vanetza/vanetza/net/sockaddr.cpp:6:10: fatal error: 'netpacket/packet.h' file not found
#include <netpacket/packet.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [vanetza/net/CMakeFiles/net.dir/sockaddr.cpp.o] Error 1
make[1]: *** [vanetza/net/CMakeFiles/net.dir/all] Error 2
make: *** [all] Error 2
```

Form what I've read on Google, it seems that OSX doesn't include `netpacket/packet.h`. Any experience with OSX or advice on how to continue?

--
OSX 10.14.6
XCode Command Line Tools installed

**Comment by riebl** [comment]
`net/sockaddr.hpp` contains only a single convenience function but is not actively used by any Vanetza code at the moment. Hence, you can safely exclude it from the build process by disabling the `VANETZA_NET_WITH_POSIX` CMake option.
Obviously, `sockaddr_ll` is not a POSIX but a Linux feature. So you can consider this a bug in Vanetza as well ;-)

**Comment by cdce8p** [comment]
Thanks for the quick response. The flag works 🐬
