### ISSUE TITLE
Compiler error for g++ <= 4.9

### ISSUE THREAD

**Issue by glmax** [riebl/vanetza#93]
[This initialization](https://github.com/riebl/vanetza/commit/d07e122ee0237ffdda7ac6905ae1bc8b5fbf3cd8#diff-ea272819106782e0902bd507d12546f0R681) cannot be compiled by g++ versions <= 4.9:

```
vanetza/security/region.cpp:681:77: error: cannot convert ‘const Elevation {aka const std::array<unsigned char, 2u>}’ to ‘unsigned char’ in initialization
     ThreeDLocation::Elevation elevation { ThreeDLocation::unknown_elevation };
                                                                             ^
```

I guess it works with g++ versions >= 5, but I can only say it for sure for 5.4.0.

I'm not sure whether this conversion is part of any of the features in [`CMAKE_CXX_KNOWN_FEATURES`](https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html), so that `target_compile_features(...)` could be used in `vanetza/security/CMakeLists.txt`.

A more general approach would be a version check in the main `CMakeLists.txt`, something like:

```cmake
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 5)
    message(FATAL_ERROR "At least g++-5 is required")
endif()
```

**Comment by riebl** [comment]
Oh, dear… good olde g++ 4.9 is known to have some trouble with C++11.
Do you really think we need to deal with this explicitly? `CMAKE_CXX_STANDARD` and `CMAKE_CXX_STANARD_REQUIRED` are already set to require C++11.

**Comment by glmax** [comment]
> Do you really think we need to deal with this explicitly?

Not necessarily. I just stumbled upon this because, by default, the Cohda SDK Rel 16 uses g++ 4.8 for cross-compilation for ARM instead of the 5.4 version, which is also installed.
