### ISSUE TITLE
Certificate encoding format

### ISSUE THREAD

**Issue by vashishthadeexa** [riebl/vanetza#94]
Certfy tool is used to create the root , AA and AT certificate. Can you tell me in which format the certificate is encoded (eg COER, PER, etc)?

**Comment by kelunik** [comment]
This is a custom format specified in [ETSI TS 103 097 V1.2.1](https://www.etsi.org/deliver/etsi_ts/103000_103099/103097/01.02.01_60/ts_103097v010201p.pdf)
