### ISSUE TITLE
Parametrized ASN.1 modules in ETSI TS 103 097 v1.3.1

### ISSUE THREAD

**Issue by awillecke** [riebl/vanetza#97]
We are trying to use the `EtsiTs103097Data-Encrypted` module from [ETSI TS 103 097 v1.3.1](../blob/master/asn1/TS103097v131.asn).
But the classes generated by ans1c to [EtsiTs103097Data-Encrypted.h](../blob/master/vanetza/asn1/security/EtsiTs103097Data-Encrypted.h) seem to have no functionality. 
Also, it looks like all other modules using ASN.1 parametrization ([EtsiTs103097Data-Signed](../blob/master/vanetza/asn1/security/EtsiTs103097Data-Signed.h) and [EtsiTs103097Data-SignedAndEncrypted](../blob/master/vanetza/asn1/security/EtsiTs103097Data-SignedAndEncrypted.h)) are also empty.

Is this a bug or are we  missing something?

**Comment by riebl** [comment]
I have noticed this as well. All those `EtsiTs103097Data-*` containers are basically specialisations of `Ieee1609Dot2Data`, i.e. same structure but with constraints on presence of certain sub-fields. I assume this is just how asn1c handles this kind of ASN.1 feature.

**Comment by kenog** [comment]
Hm ok. Thanks a lot for your prompt assessment! What do you think would be the intended usage of those types then? As far as I can see, there is no class definition for the `EtsiTs103097Data-*`containers. So how would you instantiate them? The only solution we see is to instantiate `Ieee1609Dot2Data` and use it according to TS 103 097. But that kind of defeats the purpose of the respective ASN.1 files in my opinion.
I tried to find some related issues in asn1c and found https://github.com/vlm/asn1c/issues/121. Maybe parametrization is still not fully supported in asn1c?

**Comment by kenog** [comment]
Okay nevermind. It turned out we just did not fully understand parametrization in ASN.1. There needs to be an explicit "implementation" of the parametrized types. I.e. additional ASN.1 types that specifies the parameter. The ETSI PKI (TS 102 941) for example defines `EnrolmentRequestMessages` etc. which do that.
Sorry for the noise :see_no_evil:
